package ai.platon.pulsar.browser

import ai.platon.pulsar.WebDriverTestBase
import ai.platon.pulsar.common.browser.BrowserType
import ai.platon.pulsar.common.browser.ProfileHealthMonitor
import ai.platon.pulsar.common.browser.fingerprint.BasicFingerprintGenerator
import ai.platon.pulsar.common.browser.fingerprint.Fingerprint
import ai.platon.pulsar.common.browser.fingerprint.FingerprintDriftDetector
import ai.platon.pulsar.common.browser.fingerprint.FingerprintValidator
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path

/**
 * Integration tests for BrowserProfile functionality.
 *
 * Tests the complete profile lifecycle including creation, loading,
 * validation, and persistence.
 */
@Tag("Integration")
class BrowserProfileIT : WebDriverTestBase() {

    @TempDir
    lateinit var tempDir: Path

    @Test
    @Disabled("Feature postponed")
    @DisplayName("test profile creation with auto-generated fingerprint")
    fun testProfileCreationWithAutoGeneratedFingerprint() {
        val contextDir = tempDir.resolve("test-profile-1")
        Files.createDirectories(contextDir)

        val profile = BrowserProfile.createNextSequential(BrowserType.PULSAR_CHROME)

        // Verify profile has a valid fingerprint
        assertNotNull(profile.fingerprint)
        assertNotNull(profile.fingerprint.userAgent)
        assertNotNull(profile.fingerprint.screenParameters)
        assertNotNull(profile.fingerprint.hardwareParameters)
        assertNotNull(profile.fingerprint.geoTimeParameters)

        println("✓ Profile created with fingerprint: ${profile.fingerprint.userAgent?.take(50)}...")
    }

    @Test
    @DisplayName("test fingerprint persistence to JSON file")
    fun testFingerprintPersistence() {
        val contextDir = tempDir.resolve("test-profile-2")
        Files.createDirectories(contextDir)

        // Create profile with fingerprint
        val generator = BasicFingerprintGenerator()
        val originalFingerprint = generator.generate(
            BrowserType.PULSAR_CHROME,
            BasicFingerprintGenerator.DevicePreset.DESKTOP_WINDOWS
        )

        val profile = BrowserProfile(contextDir, originalFingerprint)

        // Save fingerprint
        val fingerprintPath = contextDir.resolve("fingerprint.json")
        val json = ai.platon.pulsar.common.serialize.json.prettyPulsarObjectMapper()
            .writeValueAsString(originalFingerprint)
        Files.writeString(fingerprintPath, json)

        // Verify file was created
        assertTrue(Files.exists(fingerprintPath))

        // Load fingerprint from file
        val loadedFingerprint = ai.platon.pulsar.common.serialize.json.pulsarObjectMapper()
            .readValue(fingerprintPath.toFile(), Fingerprint::class.java)

        // Verify loaded fingerprint matches original
        assertEquals(originalFingerprint.browserType, loadedFingerprint.browserType)
        assertEquals(originalFingerprint.userAgent, loadedFingerprint.userAgent)
        assertEquals(originalFingerprint.screenParameters?.width, loadedFingerprint.screenParameters?.width)
        assertEquals(originalFingerprint.hardwareParameters?.platform, loadedFingerprint.hardwareParameters?.platform)

        println("✓ Fingerprint persisted and loaded successfully")
    }

    @Test
    @DisplayName("test fingerprint validation on load")
    fun testFingerprintValidationOnLoad() {
        val contextDir = tempDir.resolve("test-profile-3")
        Files.createDirectories(contextDir)

        // Create a valid fingerprint
        val generator = BasicFingerprintGenerator()
        val fingerprint = generator.generate(
            BrowserType.PULSAR_CHROME,
            BasicFingerprintGenerator.DevicePreset.LAPTOP_WINDOWS
        )

        // Save it
        val fingerprintPath = contextDir.resolve("fingerprint.json")
        val json = ai.platon.pulsar.common.serialize.json.prettyPulsarObjectMapper()
            .writeValueAsString(fingerprint)
        Files.writeString(fingerprintPath, json)

        // Load and validate
        val validator = FingerprintValidator()
        val loadedFingerprint = ai.platon.pulsar.common.serialize.json.pulsarObjectMapper()
            .readValue(fingerprintPath.toFile(), Fingerprint::class.java)

        val validationResult = validator.validate(loadedFingerprint)

        // Should be valid
        assertTrue(
            validationResult.isValid,
            "Fingerprint should be valid. Errors: ${validationResult.errors}"
        )

        println("✓ Loaded fingerprint passed validation: ${validationResult.summary()}")
    }

    @Test
    @Disabled("Feature postponed")
    @DisplayName("test health monitoring on profile")
    fun testHealthMonitoringOnProfile() {
        val contextDir = tempDir.resolve("test-profile-4")
        Files.createDirectories(contextDir)

        // Create complete fingerprint
        val generator = BasicFingerprintGenerator()
        val fingerprint = generator.generate(
            BrowserType.PULSAR_CHROME,
            BasicFingerprintGenerator.DevicePreset.MACBOOK_PRO_13
        )

        val profile = BrowserProfile(contextDir, fingerprint)

        // Check health
        val monitor = ProfileHealthMonitor()
        val report = monitor.checkHealth(fingerprint, contextDir)

        // Should be healthy
        assertTrue(report.isHealthy,
            "Profile should be healthy. Failed checks: ${report.failedChecks}")

        println("✓ Profile health check passed:")
        report.checks.forEach { println("  $it") }
    }

    @Test
    @Disabled("Feature postponed")
    @DisplayName("test drift detection between sessions")
    fun testDriftDetectionBetweenSessions() {
        val contextDir = tempDir.resolve("test-profile-5")
        Files.createDirectories(contextDir)

        // Create original fingerprint
        val generator = BasicFingerprintGenerator()
        val original = generator.generate(
            BrowserType.PULSAR_CHROME,
            BasicFingerprintGenerator.DevicePreset.DESKTOP_LINUX
        )

        // Simulate a modified fingerprint (as if it drifted)
        val modified = original.copy(
            screenParameters = original.screenParameters?.copy(width = 2560, height = 1440)
        )

        // Detect drift
        val detector = FingerprintDriftDetector()
        val report = detector.detectDrift(original, modified)

        // Should detect drift
        assertTrue(report.hasDrift, "Should detect fingerprint drift")
        assertTrue(report.drifts.any { it.contains("Screen resolution changed") })

        println("✓ Drift detection working:")
        println("  ${report.summary()}")
        report.drifts.forEach { println("    - $it") }
    }

    @Test
    @DisplayName("test cross-session fingerprint stability")
    fun testCrossSessionFingerprintStability() {
        val contextDir = tempDir.resolve("test-profile-6")
        Files.createDirectories(contextDir)

        // Create and save fingerprint
        val generator = BasicFingerprintGenerator()
        val fingerprint = generator.generate(
            BrowserType.PULSAR_CHROME,
            BasicFingerprintGenerator.DevicePreset.LAPTOP_WINDOWS
        )

        val fingerprintPath = contextDir.resolve("fingerprint.json")
        val json = ai.platon.pulsar.common.serialize.json.prettyPulsarObjectMapper()
            .writeValueAsString(fingerprint)
        Files.writeString(fingerprintPath, json)

        // Simulate multiple session loads
        val loadedFingerprints = mutableListOf<Fingerprint>()
        repeat(3) {
            val loaded = ai.platon.pulsar.common.serialize.json.pulsarObjectMapper()
                .readValue(fingerprintPath.toFile(), Fingerprint::class.java)
            loadedFingerprints.add(loaded)
        }

        // All loaded fingerprints should be identical (stable)
        val detector = FingerprintDriftDetector()
        for (i in 1 until loadedFingerprints.size) {
            val report = detector.detectDrift(loadedFingerprints[0], loadedFingerprints[i])
            assertFalse(report.hasDrift,
                "Fingerprint should remain stable across loads. Drift detected: ${report.drifts}")
        }

        println("✓ Fingerprint remained stable across 3 session loads")
    }

    @Test
    @DisplayName("test profile with different device presets")
    fun testProfileWithDifferentDevicePresets() {
        val generator = BasicFingerprintGenerator()
        val presets = listOf(
            BasicFingerprintGenerator.DevicePreset.DESKTOP_WINDOWS,
            BasicFingerprintGenerator.DevicePreset.LAPTOP_WINDOWS,
            BasicFingerprintGenerator.DevicePreset.MACBOOK_PRO_13,
            BasicFingerprintGenerator.DevicePreset.MACBOOK_AIR,
            BasicFingerprintGenerator.DevicePreset.DESKTOP_LINUX,
            BasicFingerprintGenerator.DevicePreset.LAPTOP_LINUX
        )

        val validator = FingerprintValidator()

        presets.forEach { preset ->
            val fingerprint = generator.generate(BrowserType.PULSAR_CHROME, preset)
            val result = validator.validate(fingerprint)

            assertTrue(result.isValid,
                "Preset $preset should generate valid fingerprint. Errors: ${result.errors}")

            println("✓ Preset $preset validated successfully")
        }
    }
}
