package ai.platon.pulsar.chrome.dom

import ai.platon.pulsar.chrome.dom.impl.AccessibilityHandler
import ai.platon.pulsar.chrome.dom.impl.AccessibilityHandler.AccessibilityTreeResult
import ai.platon.pulsar.chrome.dom.impl.DomSnapshotHandler
import ai.platon.pulsar.chrome.dom.impl.DomTreeHandler
import ai.platon.pulsar.chrome.dom.impl.OptimizedDOMTreeBuilder
import ai.platon.pulsar.chrome.dom.util.DomDebug
import ai.platon.pulsar.chrome.dom.util.HashUtils
import ai.platon.pulsar.chrome.dom.util.ScrollUtils
import ai.platon.pulsar.chrome.dom.util.XPathUtils
import ai.platon.cdt.kt.protocol.types.accessibility.AXNode
import ai.platon.pulsar.browser.impl.BrowserProtocol
import ai.platon.pulsar.chrome.dom.SnapshotService
import ai.platon.pulsar.chrome.dom.model.*
import ai.platon.pulsar.common.getLogger
import ai.platon.pulsar.common.math.geometric.DimI
import java.util.*

/**
 * Core service for collecting and merging DOM, accessibility, and snapshot data into a unified DOMState.
 *
 * ## Browser architecture context:
 *
 * ```
 * Browser
 *  └─ Window
 *      └─ Tab
 *          └─ Page (navigation instance)
 *              └─ Frame Tree
 *                  └─ Document
 *                      └─ DOM Tree
 *                          └─ Layout Tree
 *                          └─ Accessibility Tree
 *                              └─ Snapshot
 *```
 *
 * ## Chromium Rendering Architecture: The Four-Layer Core Structure:
 *
 * ```
 * DOM Tree
 *    ↓
 * Layout Tree (Render Tree)
 *    ↓
 * Accessibility Tree (AX Tree)
 *    ↓
 * Compositing Layer Tree
 * ```
 *
 * ### DOM Tree (Structure Layer)
 * The DOM is the object tree generated by the browser parsing HTML.
 *
 * ### Layout Tree (Layout Layer)
 * The Layout Tree is the visual tree calculated from DOM and CSSOM, containing the geometric information of elements.
 *
 * ```
 * DOM + CSS
 *       ↓
 * Layout Tree
 * ```
 *
 * ### Accessibility Tree（AX Tree）
 *
 * The AX Tree is the semantic tree generated by the browser for assistive technology.
 *
 * ```
 * DOM + ARIA + Layout
 *        ↓
 * Accessibility Tree
 * ```
 *
 * ### Compositing Layer Tree (Compositing Layer)
 * To enable GPU acceleration, the browser breaks the page into multiple Compositing Layers.
 *
 * ```
 * Layout Tree
 *      ↓
 * Layerization
 *      ↓
 * Compositing Layer Tree
 * ```
 */
class CDPSnapshotService(
    private val bp: BrowserProtocol,
) : SnapshotService {
    private val logger = getLogger(this)
    private val tracer get() = logger.takeIf { it.isTraceEnabled }

    private val accessibility = AccessibilityHandler(bp)
    private val domTree = DomTreeHandler(bp)
    private val snapshot = DomSnapshotHandler(bp)
    private val highlightManager = HighlightManager(bp)
    private val clickableDetector = ClickableElementDetector()

    @Volatile
    private var lastEnhancedRoot: MergedDOMTreeNode? = null

    @Volatile
    private var lastAncestorMap: Map<Int, List<MergedDOMTreeNode>> = emptyMap()

    @Volatile
    private var lastDomByBackend: Map<Int, MergedDOMTreeNode> = emptyMap()

    override suspend fun getBrowserUseState(
        target: PageTarget,
        snapshotOptions: SnapshotOptions
    ): BrowserUseState {
        val domState = getDOMState(target, snapshotOptions)
        return buildBrowserState(domState)
    }

    override suspend fun getDOMState(
        target: PageTarget,
        snapshotOptions: SnapshotOptions
    ): DOMState {
        val allTrees = buildTargetTrees(options = snapshotOptions)
        if (logger.isDebugEnabled) {
            logger.debug("allTrees summary: \n{}", DomDebug.summarize(allTrees))
        }

        val tinyTree = buildOptimizedDOMTreeNode(allTrees)
        if (logger.isDebugEnabled) {
            logger.debug("tinyTree summary: \n{}", DomDebug.summarize(tinyTree))
        }

        val domState = buildDOMState(tinyTree)
        if (logger.isDebugEnabled) {
            val json = DOMSerializer.toJson(domState.serializableTree)
            logger.debug("browserState summary: \n{}", DomDebug.summarize(domState))
            logger.debug("browserState.json: \nlength: {}\n{}", json.length, json)
        }

        return domState
    }

    suspend fun buildTargetTrees(
        target: PageTarget = PageTarget(),
        options: SnapshotOptions = SnapshotOptions()
    ): TargetTrees {
        val startTime = System.currentTimeMillis()
        val cdpTiming = mutableMapOf<String, Long>()

        // Fetch AX tree (resilient)
        val axStart = System.currentTimeMillis()
        val axTree = getAccessibilityTree(target, options)
        cdpTiming["ax_tree"] = System.currentTimeMillis() - axStart

        // Fetch DOM tree (resilient)
        val domStart = System.currentTimeMillis()
        val domTree = runCatching { this.domTree.getDocument(target, options.maxDepth) }
            .onFailure { e ->
                logger.warn("DOM tree collection failed | frameId={} | err={}", target.frameId, e.toString())
                tracer?.trace("DOM tree exception", e)
            }.getOrElse { MergedDOMTreeNode() }
        val domByBackendId = runCatching { this.domTree.lastBackendNodeLookup() }.getOrDefault(emptyMap())
        cdpTiming["dom_tree"] = System.currentTimeMillis() - domStart

        // Get device pixel ratio first for snapshot scaling
        val dprStart = System.currentTimeMillis()
        val devicePixelRatio = runCatching { getDevicePixelRatio() }.getOrDefault(1.0)
        cdpTiming["dpr"] = System.currentTimeMillis() - dprStart

        // Fetch snapshot (resilient)
        val snapshotStart = System.currentTimeMillis()
        val snapshotByBackendId = if (options.includeSnapshot) {
            runCatching {
                snapshot.captureSnapshot(
                    includeStyles = options.includeStyles,
                    includePaintOrder = options.includePaintOrder,
                    includeDomRects = options.includeDOMRects,
                    includeAbsoluteCoords = true,
                    devicePixelRatio = devicePixelRatio
                )
            }.onFailure { e ->
                logger.warn("Snapshot collection failed | err={} ", e.toString())
                tracer?.trace("Snapshot exception", e)
            }.getOrDefault(emptyMap())
        } else {
            emptyMap()
        }
        cdpTiming["snapshot"] = System.currentTimeMillis() - snapshotStart

        // Build AX mappings
        val enhancedAXTree = axTree.nodes.map { it.toEnhanced() }
        val axByBackendId: Map<Int, AXNodeEx> = buildMap {
            axTree.nodesByBackendNodeId.forEach { (backendId, nodes) ->
                val first = nodes.firstOrNull() ?: return@forEach
                put(backendId, first.toEnhanced())
            }
        }

        val axTreeByFrameId: Map<String, List<AXNodeEx>> = axTree.nodesByFrameId.mapValues { (_, list) ->
            list.map { it.toEnhanced() }
        }

        cdpTiming["total"] = System.currentTimeMillis() - startTime

        tracer?.trace(
            "Trees collected | axNodes={} snapEntries={} dpr={} timingsMs={} ",
            enhancedAXTree.size, snapshotByBackendId.size, devicePixelRatio, cdpTiming
        )

        return TargetTrees(
            domTree = domTree,
            axTree = enhancedAXTree,
            snapshotByBackendId = snapshotByBackendId,
            axByBackendId = axByBackendId,
            axTreeByFrameId = axTreeByFrameId,
            devicePixelRatio = devicePixelRatio,
            cdpTiming = cdpTiming,
            options = options,
            domByBackendId = domByBackendId
        )
    }

    /**
     * Build a merged DOM tree from all trees (DOM, AX, Snapshot) with enhanced metrics, frame-aware offsets, and robust error handling.
     * */
    fun buildMergedDOMTreeNode(trees: TargetTrees): MergedDOMTreeNode {
        val options = trees.options
        // Build ancestor map for XPath and hash generation
        val ancestorMap = buildAncestorMap(trees.domTree)
        lastAncestorMap = ancestorMap
        lastDomByBackend = trees.domByBackendId

        // Build sibling map for XPath index calculation
        val siblingMap = buildSiblingMap(trees.domTree)

        fun visibilityStyleCheck(snapshotNode: SnapshotNodeEx?): Boolean? {
            snapshotNode ?: return null

            val styles = snapshotNode.computedStyles ?: return null

            val display = styles["display"]
            if (display != null && display.equals("none", true)) return false

            val visibility = styles["visibility"]
            if (visibility != null && visibility.equals("hidden", true)) return false

            val opacity = styles["opacity"]?.toDoubleOrNull()
            if (opacity != null && opacity <= 0.0) return false

            val pointerEvents = styles["pointer-events"]
            if (pointerEvents != null && pointerEvents.equals("none", true)) return false

            return true
        }

        fun isElementVisibleAccordingToAllParents(
            node: MergedDOMTreeNode,
            htmlFrames: List<MergedDOMTreeNode>
        ): Boolean {
            val snap = node.snapshotNode ?: return false
            var current = snap.bounds?.roundTo(1)
                ?.let { DOMRect(it.x, it.y, it.width, it.height) } ?: return false

            // Reverse iterate through frame stack
            for (frame in htmlFrames.asReversed()) {
                val tag = frame.nodeName.uppercase()
                val fsnap = frame.snapshotNode
                if (tag == "IFRAME" || tag == "FRAME") {
                    val fb = fsnap?.bounds?.roundTo(1)
                    if (fb != null) {
                        current = DOMRect(current.x + fb.x, current.y + fb.y, current.width, current.height)
                    }
                }
                if (tag == "HTML" && fsnap?.scrollRects != null && fsnap.clientRects != null) {
                    val viewportLeft = 0.0
                    val viewportTop = 0.0
                    val viewportRight = fsnap.clientRects.width
                    val viewportBottom = fsnap.clientRects.height

                    val adjustedX = current.x - fsnap.scrollRects.x
                    val adjustedY = current.y - fsnap.scrollRects.y

                    val intersects = adjustedX < viewportRight &&
                            adjustedX + current.width > viewportLeft &&
                            adjustedY < viewportBottom + 1000 &&
                            adjustedY + current.height > viewportTop - 1000
                    if (!intersects) return false

                    // Keep adjustment like Python for proper propagation
                    current = DOMRect(adjustedX, adjustedY, current.width, current.height)
                }
            }
            return true
        }

        // Merge trees recursively with enhanced metrics and frame-aware offsets
        fun merge(
            node: MergedDOMTreeNode,
            ancestors: List<MergedDOMTreeNode>,
            htmlFrames: List<MergedDOMTreeNode>,
            offsetX: Double,
            offsetY: Double,
            depth: Int = 0
        ): MergedDOMTreeNode {
            val backendNodeId = node.backendNodeId

            // Get snapshot and AX
            val snapshot =
                if (options.includeSnapshot && backendNodeId != null) trees.snapshotByBackendId[backendNodeId] else null
            val ax = if (options.includeAX && backendNodeId != null) trees.axByBackendId[backendNodeId] else null

            // Calculate absolute position based on accumulated offsets
            val absolutePosition = snapshot?.bounds?.roundTo(1)
                ?.let { DOMRect(it.x + offsetX, it.y + offsetY, it.width, it.height) }

            // Visibility: style check first, then frame viewport check
            val isVisible = if (options.includeVisibility) {
                val styleVisible = visibilityStyleCheck(snapshot)
                if (styleVisible == false) false else isElementVisibleAccordingToAllParents(
                    node.copy(snapshotNode = snapshot), htmlFrames
                )
            } else null

            // Interactivity and indices
            val isScrollable = if (options.includeScrollAnalysis) {
                calculateScrollability(node, snapshot, ancestors)
            } else null

            val isInteractable = if (options.includeInteractivity) {
                calculateInteractivity(node, snapshot, null)
            } else null

            val interactiveIndex = if (options.includeInteractivity && snapshot?.paintOrder != null) {
                calculateInteractiveIndex(snapshot, null, snapshot.paintOrder)
            } else null

            // XPath and hashes
            val xpath = runCatching { XPathUtils.generateXPath(node, ancestors, siblingMap) }
                .onFailure { tracer?.trace("XPath generation failed | nodeId={} | {} ", node.nodeId, it.toString()) }
                .getOrNull()

            val parentBranchHash = if (ancestors.isNotEmpty()) {
                runCatching { HashUtils.parentBranchHash(ancestors) }
                    .onFailure {
                        tracer?.trace(
                            "Parent branch hash failed | nodeId={} | {} ",
                            node.nodeId,
                            it.toString()
                        )
                    }
                    .getOrNull()
            } else null

            val elementHash = runCatching { HashUtils.elementHash(node, parentBranchHash) }
                .onFailure { tracer?.trace("Element hash failed | nodeId={} | {} ", node.nodeId, it.toString()) }
                .getOrNull()

            val mergedNode = node.copy(
                snapshotNode = snapshot,
                axNode = ax,
                isScrollable = isScrollable,
                isVisible = isVisible,
                isInteractable = isInteractable,
                interactiveIndex = interactiveIndex,
                absolutePosition = absolutePosition,
                xpath = xpath,
                elementHash = elementHash,
                parentBranchHash = parentBranchHash
            )

            val newAncestors = ancestors + mergedNode

            // Update frame stack and offsets for descendants
            var nextHtmlFrames = htmlFrames
            var nextOffsetX = offsetX
            var nextOffsetY = offsetY

            val tag = node.nodeName.uppercase()
            if (tag == "HTML") {
                nextHtmlFrames = htmlFrames + mergedNode
                if (snapshot?.scrollRects != null) {
                    nextOffsetX -= snapshot.scrollRects.x
                    nextOffsetY -= snapshot.scrollRects.y
                }
            }

            val mergedChildren = node.children.map { child ->
                merge(child, newAncestors, nextHtmlFrames, nextOffsetX, nextOffsetY, depth + 1)
            }

            val mergedShadowRoots = node.shadowRoots.map { shadow ->
                merge(shadow, newAncestors, nextHtmlFrames, nextOffsetX, nextOffsetY, depth + 1)
            }

            var mergedContentDocument: MergedDOMTreeNode? = null
            if (node.contentDocument != null) {
                // If current node is an IFRAME/FRAME, push frame and add its bounds to offset for content doc
                var cFrames = nextHtmlFrames
                var cOffsetX = nextOffsetX
                var cOffsetY = nextOffsetY
                if (tag == "IFRAME" || tag == "FRAME") {
                    cFrames = nextHtmlFrames + mergedNode
                    val b = snapshot?.bounds?.roundTo(1)
                    if (b != null) {
                        cOffsetX += b.x
                        cOffsetY += b.y
                    }
                }
                mergedContentDocument =
                    merge(node.contentDocument, newAncestors, cFrames, cOffsetX, cOffsetY, depth + 1)
            }

            return mergedNode.copy(
                children = mergedChildren,
                shadowRoots = mergedShadowRoots,
                contentDocument = mergedContentDocument
            )
        }

        val merged = merge(trees.domTree, emptyList(), emptyList(), 0.0, 0.0)
        lastEnhancedRoot = merged
        return merged
    }

    internal fun buildOptimizedDOMTreeNode(trees: TargetTrees): OptimizedDOMTree {
        val enhanced = buildMergedDOMTreeNode(trees)
        val hasElements = enhanced.children.isNotEmpty() ||
                enhanced.shadowRoots.isNotEmpty() ||
                enhanced.contentDocument != null
        val optimizedTree = OptimizedDOMTreeBuilder(enhanced).build()

        if (!hasElements || optimizedTree == null) {
            logger.info("Empty DOM tree collected | trees: {}", DomDebug.summarize(trees))
            // throw IllegalStateException("Empty DOM tree collected (AX=${trees.axTree.size}, SNAP=${trees.snapshotByBackendId.size})")
        }

        return optimizedTree ?: OptimizedDOMTree(MergedDOMTreeNode())
    }

    fun buildOptimizedDOMTreeNode(root: MergedDOMTreeNode): OptimizedDOMTreeNode {
        fun optimize(node: MergedDOMTreeNode): OptimizedDOMTreeNode {
            val optimizedChildren = node.children.map { optimize(it) }

            return OptimizedDOMTreeNode(
                originalNode = node,
                children = optimizedChildren,
                shouldDisplay = node.nodeType == NodeType.ELEMENT_NODE ||
                        node.nodeType == NodeType.TEXT_NODE,
                interactiveIndex = node.interactiveIndex
            )
        }

        return optimize(root)
    }

    fun buildDOMState(root: OptimizedDOMTreeNode, includeAttributes: List<String> = emptyList()): DOMState {
        // Use enhanced serialization with default options
        val options = DOMStateBuilder.CompactOptions(
            enablePaintOrderPruning = true,
            enableCompoundComponentDetection = true,
            enableAttributeCasingAlignment = true
        )
        return DOMStateBuilder.build(root, includeAttributes, options)
    }

    /**
     * Safely evaluate a JS expression and return the result as a Double.
     */
    private suspend fun evalDouble(expr: String): Double? {
        return try {
            val result = bp.evaluate(expr).result
            result.value?.toString()?.toDoubleOrNull() ?: result.unserializableValue?.toDoubleOrNull()
        } catch (e: Exception) {
            tracer?.trace("Evaluation error | expr={} | err={}", expr, e.toString())
            null
        }
    }

    /**
     * Safely evaluate a JS expression and return the result as an Int.
     */
    private suspend fun evalInt(expr: String): Int? = evalDouble(expr)?.toInt()

    /**
     * Safely evaluate a JS expression and return the result as a String.
     */
    private suspend fun evalString(expr: String): String? = try {
        bp.evaluate(expr).result.value?.toString()
    } catch (e: Exception) {
        tracer?.trace("Evaluation error | expr={} | err={}", expr, e.toString())
        null
    }

    /**
     * Safely evaluate a JS expression and return the result as a Boolean.
     */
    private suspend fun evalBoolean(expr: String): Boolean? = try {
        val v = bp.evaluate(expr).result.value
        when (v) {
            is Boolean -> v
            is String -> v.equals("true", true)
            is Number -> v.toInt() != 0
            else -> null
        }
    } catch (e: Exception) {
        tracer?.trace("Evaluation error | expr={} | err={}", expr, e.toString())
        null
    }

    private suspend fun buildBrowserState(domState: DOMState): BrowserUseState {
        // URL from DOM domain (resilient)
        val url: String = runCatching { bp.getDocument().documentURL }.getOrNull() ?: ""

        // Navigation history for back/forward URLs (resilient)

        val (goBackUrl, goForwardUrl) = runCatching {
            val history = bp.getNavigationHistory()
            val currentIndex = history.currentIndex
            val entries = history.entries

            val back = entries.getOrNull(currentIndex - 1)?.url
            val forward = entries.getOrNull(currentIndex + 1)?.url
            back to forward
        }.getOrElse { "" to "" }

        // Scroll positions and viewport size (resilient)
        val scrollX = evalDouble("window.scrollX || window.pageXOffset || 0") ?: 0.0
        val scrollY = evalDouble("window.scrollY || window.pageYOffset || 0") ?: 0.0
        val viewportWidth =
            (evalDouble("window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth || 0")
                ?: 0.0).toInt()
        val viewportHeight =
            (evalDouble("window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight || 0")
                ?: 0.0).toInt()

        // Screen DimIs
        val screenWidth = evalInt("(window.screen && window.screen.width) || 0") ?: 0
        val screenHeight = evalInt("(window.screen && window.screen.height) || 0") ?: 0

        // Compute max vertical scroll and ratio
        val totalHeight =
            evalDouble("(document.scrollingElement || document.documentElement || document.body).scrollHeight")
                ?: viewportHeight.toDouble()
        val clientHeight =
            evalDouble("(document.scrollingElement || document.documentElement || document.body).clientHeight")
                ?: viewportHeight.toDouble()
        val maxScrollY = (totalHeight - clientHeight).let { if (it.isFinite() && it > 0) it else 0.0 }
        val scrollYRatio = if (maxScrollY > 0) (scrollY / maxScrollY).coerceIn(0.0, 1.0) else 0.0

        val scrollState = ScrollState(
            x = scrollX,
            y = scrollY,
            viewport = DimI(viewportWidth, viewportHeight),
            totalHeight = totalHeight,
            scrollYRatio = scrollYRatio
        )

        // Client info from browser (fallback to system defaults)
        val tzId = runCatching {
            bp.evaluate("Intl.DateTimeFormat().resolvedOptions().timeZone").result.value?.toString()
        }.getOrNull()?.takeIf { it.isNotBlank() }
        val timeZone = runCatching { if (tzId != null) TimeZone.getTimeZone(tzId) else TimeZone.getDefault() }
            .getOrDefault(TimeZone.getDefault())

        val langTag = runCatching {
            bp.evaluate("navigator.language || (navigator.languages && navigator.languages[0]) || ''").result.value?.toString()
        }.getOrNull()?.takeIf { it.isNotBlank() }
        val locale = runCatching { if (langTag != null) Locale.forLanguageTag(langTag) else Locale.getDefault() }
            .getOrDefault(Locale.getDefault())

        val clientInfo = ClientInfo(
            timeZone = timeZone.id,
            locale = locale,
            viewportWidth = viewportWidth,
            viewportHeight = viewportHeight,
            screenWidth = screenWidth,
            screenHeight = screenHeight
        )

        val browserState = BrowserState(
            url = url,
            goBackUrl = goBackUrl,
            goForwardUrl = goForwardUrl,
            clientInfo = clientInfo,
            scrollState = scrollState
        )

        return BrowserUseState(browserState, domState)
    }

    /**
     * Reserved.
     * */
    suspend fun computeFullClientInfo(): FullClientInfo {
        val tzId = evalString("Intl.DateTimeFormat().resolvedOptions().timeZone")
        val timeZone = runCatching { if (!tzId.isNullOrBlank()) TimeZone.getTimeZone(tzId) else TimeZone.getDefault() }
            .getOrDefault(TimeZone.getDefault())

        val langTag = evalString("navigator.language || (navigator.languages && navigator.languages[0]) || ''")
        val locale =
            runCatching { if (!langTag.isNullOrBlank()) Locale.forLanguageTag(langTag) else Locale.getDefault() }
                .getOrDefault(Locale.getDefault())

        val userAgent = evalString("navigator.userAgent")
        val devicePixelRatio = runCatching { getDevicePixelRatio() }.getOrDefault(1.0)
        val viewportWidth =
            evalInt("window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth || 0")
        val viewportHeight =
            evalInt("window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight || 0")
        val screenWidth = evalInt("(window.screen && window.screen.width) || 0")
        val screenHeight = evalInt("(window.screen && window.screen.height) || 0")
        val colorDepth = evalInt("(window.screen && (screen.colorDepth || screen.pixelDepth)) || 0")
        val hardwareConcurrency = evalInt("navigator.hardwareConcurrency || 0")
        val deviceMemoryGB = evalDouble("navigator.deviceMemory || 0")
        val onLine = evalBoolean("navigator.onLine")
        val networkEffectiveType = evalString("(navigator.connection && navigator.connection.effectiveType) || ''")
        val saveData = evalBoolean("(navigator.connection && navigator.connection.saveData) || false")
        val prefersDarkMode =
            evalBoolean("(window.matchMedia && matchMedia('(prefers-color-scheme: dark)').matches) || false")
        val prefersReducedMotion =
            evalBoolean("(window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches) || false")
        val isSecureContext = evalBoolean("isSecureContext")
        val crossOriginIsolated = evalBoolean("crossOriginIsolated")
        val doNotTrack = evalString("navigator.doNotTrack || ''")
        val webdriver = evalBoolean("navigator.webdriver || false")
        val historyLength = evalInt("history.length || 0")
        val visibilityState = evalString("document.visibilityState || ''")

        return FullClientInfo(
            timeZone = timeZone.id,
            locale = locale,
            userAgent = userAgent,
            devicePixelRatio = devicePixelRatio,
            viewportWidth = viewportWidth,
            viewportHeight = viewportHeight,
            screenWidth = screenWidth,
            screenHeight = screenHeight,
            colorDepth = colorDepth,
            hardwareConcurrency = hardwareConcurrency,
            deviceMemoryGB = deviceMemoryGB,
            onLine = onLine,
            networkEffectiveType = networkEffectiveType,
            saveData = saveData,
            prefersDarkMode = prefersDarkMode,
            prefersReducedMotion = prefersReducedMotion,
            isSecureContext = isSecureContext,
            crossOriginIsolated = crossOriginIsolated,
            doNotTrack = doNotTrack,
            webdriver = webdriver,
            historyLength = historyLength,
            visibilityState = visibilityState,
        )
    }

    override fun findElement(ref: ElementRefCriteria): MergedDOMTreeNode? {
        val root = requireNotNull(lastEnhancedRoot) { "Enhanced DOM tree not built yet" }

        // Try element hash first (fastest)
        ref.elementHash?.let { hash ->
            findByDfs(root) { it.elementHash == hash }?.let { return it }
        }

        // Try XPath
        ref.xPath?.let { xpath ->
            findByDfs(root) { it.xpath == xpath }?.let { return it }
        }

        // Try backend node ID
        ref.backendNodeId?.let { backendId ->
            lastDomByBackend[backendId]?.let { return it }
            findByDfs(root) { it.backendNodeId == backendId }?.let { return it }
        }

        // Try CSS selector (simple cases only)
        ref.cssSelector?.let { selector ->
            val matcher = buildCssMatcher(selector)
            findByDfs(root, matcher)?.let { return it }
        }

        return null
    }

    /**
     * Depth-first search for the first node matching the predicate.
     */
    private fun findByDfs(root: MergedDOMTreeNode, predicate: (MergedDOMTreeNode) -> Boolean): MergedDOMTreeNode? {
        if (predicate(root)) return root
        root.children.forEach { child -> findByDfs(child, predicate)?.let { return it } }
        root.shadowRoots.forEach { shadow -> findByDfs(shadow, predicate)?.let { return it } }
        root.contentDocument?.let { doc -> findByDfs(doc, predicate)?.let { return it } }
        return null
    }

    /**
     * Build a CSS selector matcher for simple selectors (tag, #id, .class).
     */
    private fun buildCssMatcher(selector: String): (MergedDOMTreeNode) -> Boolean {
        val tagRegex = Regex("^[a-zA-Z0-9]+")
        val idRegex = Regex("#([a-zA-Z0-9_-]+)")
        val classRegex = Regex("\\.([a-zA-Z0-9_-]+)")

        val tag = tagRegex.find(selector)?.value?.lowercase()
        val id = idRegex.find(selector)?.groupValues?.getOrNull(1)
        val classes = classRegex.findAll(selector).map { it.groupValues[1] }.toSet()

        return { n: MergedDOMTreeNode ->
            (tag == null || n.nodeName.equals(tag, ignoreCase = true)) &&
                    (id == null || n.attributes["id"] == id) &&
                    (classes.isEmpty() || classes.all {
                        it in (n.attributes["class"]?.split(Regex("\\s+"))?.toSet() ?: emptySet())
                    })
        }
    }

    fun toInteractedElement(node: MergedDOMTreeNode): DOMInteractedElement {
        return DOMInteractedElement(
            elementHash = node.elementHash ?: HashUtils.simpleElementHash(node),
            xpath = node.xpath,
            bounds = node.snapshotNode?.clientRects?.roundTo(1),
            isVisible = node.isVisible,
            isInteractable = node.isInteractable
        )
    }

    private suspend fun getDevicePixelRatio(): Double {
        return try {
            val evaluation = bp.evaluate("window.devicePixelRatio")
            val result = evaluation.result
            val numeric = result.value?.toString()?.toDoubleOrNull()
            numeric ?: result.unserializableValue?.toDoubleOrNull() ?: 1.0
        } catch (e: Exception) {
            logger.debug("Device pixel ratio fallback | err={}", e.toString())
            1.0
        }
    }

    /**
     * Build a map of node ID to ancestors for efficient path calculation.
     */
    private fun buildAncestorMap(root: MergedDOMTreeNode): Map<Int, List<MergedDOMTreeNode>> {
        val map = mutableMapOf<Int, List<MergedDOMTreeNode>>()

        fun traverse(node: MergedDOMTreeNode, ancestors: List<MergedDOMTreeNode>) {
            map[node.nodeId] = ancestors
            val newAncestors = ancestors + node
            node.children.forEach { traverse(it, newAncestors) }
            node.shadowRoots.forEach { traverse(it, newAncestors) }
            node.contentDocument?.let { traverse(it, newAncestors) }
        }

        traverse(root, emptyList())
        return map
    }

    /**
     * Build a map of parent node ID to children for index calculation.
     */
    private fun buildSiblingMap(root: MergedDOMTreeNode): Map<Int, List<MergedDOMTreeNode>> {
        val map = mutableMapOf<Int, List<MergedDOMTreeNode>>()

        fun traverse(node: MergedDOMTreeNode) {
            if (node.children.isNotEmpty()) {
                map[node.nodeId] = node.children
            }
            node.children.forEach { traverse(it) }
            node.shadowRoots.forEach { traverse(it) }
            node.contentDocument?.let { traverse(it) }
        }

        traverse(root)
        return map
    }

    /**
     * Calculate scrollability with enhanced logic covering iframe/body/html and nested containers.
     */
    private fun calculateScrollability(
        node: MergedDOMTreeNode,
        snap: SnapshotNodeEx?,
        ancestors: List<MergedDOMTreeNode>
    ): Boolean? {
        if (snap == null) return null

        // Use the provided snapshot for basic detection (prevents null snapshotNode on pre-merge node)
        val basicScrollable = ScrollUtils.isActuallyScrollable(
            node.copy(snapshotNode = snap)
        )
        if (!basicScrollable) return false

        // Enhanced logic for iframe/body/html special cases
        val tagName = node.nodeName.lowercase()
        val isSpecialElement = tagName in setOf("iframe", "body", "html")

        if (isSpecialElement) {
            // For special elements, check if they have meaningful scrollable content
            val scrollHeight = snap.scrollRects?.height ?: 0.0
            val clientHeight = snap.clientRects?.height ?: 0.0
            return scrollHeight > clientHeight + 1 // Allow 1px tolerance
        }

        // For nested containers, check for duplicate scrollability in ancestors
        val hasScrollableAncestor = ancestors.any { ancestor ->
            ancestor.isScrollable == true && ancestor.snapshotNode?.scrollRects != null
        }

        // If parent is already scrollable, this might be a nested scrollable that should be deduplicated
        return if (hasScrollableAncestor) {
            // Only mark as scrollable if it has significantly different scroll properties
            val ancestorScrollAreas = ancestors
                .filter { it.isScrollable == true }
                .mapNotNull { it.snapshotNode?.scrollRects }
            val currentScrollArea = snap.scrollRects ?: return true

            // Check if current element has significantly different scroll area
            ancestorScrollAreas.none { ancestorArea ->
                kotlin.math.abs(ancestorArea.x - currentScrollArea.x) < 5 &&
                        kotlin.math.abs(ancestorArea.y - currentScrollArea.y) < 5 &&
                        kotlin.math.abs(ancestorArea.width - currentScrollArea.width) < 5 &&
                        kotlin.math.abs(ancestorArea.height - currentScrollArea.height) < 5
            }
        } else {
            true
        }
    }

    /**
     * Calculate interactivity with paint order consideration.
     */
    private fun calculateInteractivity(
        node: MergedDOMTreeNode,
        snap: SnapshotNodeEx?,
        paintOrder: Int?
    ): Boolean? {
        if (snap == null) return null

        // Check if node is clickable based on cursor style
        if (snap.isClickable == true) return true

        // Check interactivity based on node type and attributes
        val tag = node.nodeName.uppercase()
        if (tag in setOf("BUTTON", "A", "INPUT", "SELECT", "TEXTAREA", "OPTION")) {
            return true
        }

        // Check AX role for interactivity
        val role = node.axNode?.role
        if (role != null && role.lowercase() in setOf("button", "link", "checkbox", "textbox", "combobox")) {
            return true
        }

        // Check cursor style
        if (snap.cursorStyle?.equals("pointer", ignoreCase = true) == true) return true

        return clickableDetector.isInteractive(node)
    }

    /**
     * Calculate interactive index based on paint order and stacking context.
     */
    private fun calculateInteractiveIndex(snap: SnapshotNodeEx, stackingContext: Int?, paintOrder: Int?): Int? {
        if (paintOrder == null) {
            return null
        }

        // Higher paint order means element is painted later (on top)
        // Lower stacking context values mean higher z-index
        val stackingFactor = (stackingContext ?: 0) * 1000
        return paintOrder + stackingFactor
    }

    private suspend fun getAccessibilityTree(target: PageTarget, options: SnapshotOptions): AccessibilityTreeResult {
        // Fetch AX tree (resilient)
        val axResult: AccessibilityTreeResult = if (options.includeAX) {
            runCatching { accessibility.getFullAXTree(target.frameId, depth = null) }
                .onFailure { e ->
                    logger.warn("AX tree collection failed | frameId={} | err={}", target.frameId, e.toString())
                    tracer?.trace("AX tree exception", e)
                }
                .getOrDefault(AccessibilityTreeResult.EMPTY)
        } else AccessibilityTreeResult.EMPTY

        return axResult
    }

    override suspend fun addHighlights(elements: InteractiveDOMTreeNodeList) {
        highlightManager.addHighlights(elements)
    }

    override suspend fun removeHighlights(force: Boolean) {
        highlightManager.removeHighlights(force)
    }

    override suspend fun removeHighlights(elements: InteractiveDOMTreeNodeList) {
        highlightManager.removeHighlights(elements)
    }
}

/**
 * Convert CDP AXNode to AXNodeEx.
 *
 * In the context of the Chrome DevTools Protocol (CDP), AXNode is a data structure that represents a single node within
 * the Accessibility Tree. It is used to programmatically inspect how a web page is exposed to assistive technologies
 * like screen readers.
 *
 * AXNode stands for Accessibility Node, which is generated by the browser's semantic inference of DOM, CSS, and ARIA,
 * used to express the "user semantic structure" of the UI.
 *
 * ## Accessibility.AXPropertyName
 *
 * **Values of AXProperty name:**
 *
 * - from 'busy' to 'roledescription': states which apply to every AX node
 * - from 'live' to 'root': attributes which apply to nodes in live regions
 * - from 'autocomplete' to 'valuetext': attributes which apply to widgets
 * - from 'checked' to 'selected': states which apply to widgets
 * - from 'activedescendant' to 'owns': relationships between elements other than parent/child/sibling
 * - from 'activeFullscreenElement' to 'uninteresting': reasons why this noode is hidden
 *
 * **Allowed Values:**
 *
 * - actions,
 * - busy, disabled, editable, focusable, focused, hidden, hiddenRoot, invalid, keyshortcuts, settable, roledescription,
 * - live, atomic, relevant, root,
 * - autocomplete, hasPopup, level, multiselectable, orientation, multiline, readonly, required, valuemin, valuemax, valuetext,
 * - checked, expanded, modal, pressed, selected,
 * - activedescendant, controls, describedby, details, errormessage, flowto, labelledby, owns,
 * - url,
 * - activeFullscreenElement, activeModalDialog, activeAriaModalDialog, ariaHiddenElement, ariaHiddenSubtree, emptyAlt, emptyText, inertElement,
 * inertSubtree, labelContainer, labelFor, notRendered, notVisible, presentationalRole, probablyPresentational,
 * inactiveCarouselTabContent, uninteresting
 *
 * **Type**: string
 *
 * @see [AXNode](https://chromedevtools.github.io/devtools-protocol/tot/Accessibility/#type-AXNode)
 */
private fun AXNode.toEnhanced(): AXNodeEx {
    val props = properties?.mapNotNull { prop ->
        try {
            AXPropertyEx(
                name = prop.name.toString(),
                value = prop.value.value
            )
        } catch (e: Exception) {
            null
        }
    }

    return AXNodeEx(
        axNodeId = nodeId,
        ignored = ignored,
        role = role?.value?.toString(),
        name = name?.value?.toString(),
        description = description?.value?.toString(),
        properties = props,
        childIds = childIds,
        backendNodeId = backendDOMNodeId,
        frameId = null
    )
}
