<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
<!--    <name>jsoup Java HTML Parser</name>-->

    <parent>
        <groupId>ai.platon.pulsar</groupId>
        <artifactId>pulsar</artifactId>
        <version>4.10.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>pulsar-jsoup</artifactId>

    <name>Pulsar Jsoup</name>

    <description>jsoup is a Java library for working with real-world HTML. It provides a very convenient API for fetching URLs and extracting and manipulating data, using the best of HTML5 DOM methods and CSS selectors. jsoup implements the WHATWG HTML5 specification, and parses HTML to the same DOM as modern browsers do.</description>
    <url>https://jsoup.org/</url>
    <inceptionYear>2009</inceptionYear>
    <issueManagement>
        <system>GitHub</system>
        <url>https://github.com/jhy/jsoup/issues</url>
    </issueManagement>
    <licenses>
        <license>
            <name>The MIT License</name>
            <url>https://jsoup.org/license</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <organization>
        <name>Jonathan Hedley</name>
        <url>https://jhy.io/</url>
    </organization>

    <dependencies>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
        </dependency>

        <!-- junit -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.8.1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <!-- gson, to fetch entities from w3.org -->
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
<!--            <version>2.8.8</version>-->
            <scope>test</scope>
        </dependency>

        <dependency>
            <!-- javax.annotations.nonnull, with Apache 2 (not GPL) license. Build time only. -->
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
        </dependencies>
    </dependencyManagement>

    <developers>
        <developer>
            <name>Vincent Zhang</name>
            <email>ivincent.zhang@gmail.com</email>
            <organization>platon.ai</organization>
            <timezone>+8</timezone>
        </developer>
    </developers>

</project>
