"use strict";

let __pulsar_utils__ = function () {
    this.fineHeight = 4000;
    this.fineNumAnchor = 100;
    this.fineNumImage = 20;

    // WeakMap to store computed visual information without polluting the live DOM.
    // Keys are live DOM Elements; values are plain objects:
    //   { vi?: string, hidden?: {attrName: string}, overflowHidden?: boolean,
    //     textNodeRects?: (string|false)[], charWidth?: string }
    this._viDataMap = new WeakMap();
    this._viDataComputed = false;

    // Map of rel -> href for <link> elements to inject during HTML serialization.
    // Populated by setCaptureMetaInfo() from Kotlin; consumed by serializeAnnotatedHTML().
    this._captureMetaLinks = {};
};

__pulsar_utils__.getConfig = function() {
    // __pulsar_CONFIGS is generated by Kotlin code
    return __pulsar_CONFIGS || __pulsar_DEFAULT_CONFIGS
}

/**
 * Fast content-length estimation using native outerHTML.
 * Returns the length of the full document's outerHTML before any custom data
 * (meta info, vi attributes, etc.) has been injected into the DOM.
 * Speed takes priority over accuracy — native outerHTML is compiled C++,
 * much faster than the JS tree-walking serializer.
 *
 * @return {number} The length of document.documentElement.outerHTML
 */
__pulsar_utils__.getOriginalContentLength = function() {
    return (document.documentElement.outerHTML || '').length;
};

/**
 * Store capture meta info that will be injected as <link> elements during
 * HTML serialization by serializeAnnotatedHTML(). This avoids DOM mutation
 * — the links appear only in the serialized output, not the live DOM.
 *
 * @param {Object} metaInfos - map of rel -> href
 */
__pulsar_utils__.setCaptureMetaInfo = function(metaInfos) {
    this._captureMetaLinks = metaInfos || {};
};

/**
 * @param scroll The count to scroll down
 * @return {Object|boolean}
 * @deprecated Use {@code __pulsar_utils__.waitForDocumentFullyLoaded()} instead
 * */
__pulsar_utils__.waitForReady = function(scroll = 3) {
    return this.waitForDocumentFullyLoaded(scroll);
};

/**
 * @param scroll The count to scroll down
 * @return {Object|boolean}
 * */
__pulsar_utils__.waitForDocumentFullyLoaded = function(scroll = 3) {
    return this.checkStatus(scroll);
};

/**
 * @param scroll The count to scroll down
 * @return {Object|boolean}
 * */
__pulsar_utils__.checkStatus = function(scroll = 3) {
    if (!document) {
        return false
    }

    if (!__pulsar_utils__.data) {
        // initialization
        this.createDataIfAbsent();
        this.__updateStat(true);
    }

    let status = __pulsar_utils__.data.trace.status;
    status.n += 1;

    if (status.scroll < scroll) {
        window.scrollBy(0, 500);
        status.scroll += 1;
    }

    let ready = this.isActuallyReady();
    if (!ready) {
        return false
    }

    if (this.isBrowserError()) {
        __pulsar_utils__.data.trace.status.ec = document.querySelector(".error-code").textContent
    }

    // The document is ready
    return JSON.stringify(__pulsar_utils__.data)
};

__pulsar_utils__.isBrowserError = function () {
    return document.documentURI.startsWith("chrome-error");
};

__pulsar_utils__.createDataIfAbsent = function() {
    if (!__pulsar_utils__.data) {
        let location;
        if (window.location instanceof Location) {
            location = window.location.href
        } else {
            location = window.location
        }

        __pulsar_utils__.data = {
            trace: {
                status: { n: 0, scroll: 0, idl: 0, st: "", r: "", ec: "" },
                initStat: null,
                lastStat: {w: 0, h: 0, na: 0, ni: 0, nst: 0, nnm: 0},
                lastD:    {w: 0, h: 0, na: 0, ni: 0, nst: 0, nnm: 0},
                initD:    {w: 0, h: 0, na: 0, ni: 0, nst: 0, nnm: 0}
            },
            urls: {
                URL: document.URL,
                baseURI: document.baseURI,
                location: location,
                documentURI: document.documentURI,
                referrer: document.referrer
            },
            metadata: null
        };
    }
};

__pulsar_utils__.writeData = function() {
    if (!document.body) {
        return false
    }

    let config = this.getConfig();
    let script = document.getElementById(config.SCRIPT_SECTION_ID);
    if (script != null) {
        return
    }

    script = document.createElement('script');
    script.id = config.SCRIPT_SECTION_ID;
    // JavaScript only (leave default type, or set a valid one for compatibility)
    script.type = 'text/javascript';

    let pulsarData = JSON.stringify(__pulsar_utils__.data, null, 3);
    script.textContent = "\n" + `;let __pulsar__Data = ${pulsarData};\n`;

    document.body.appendChild(script);
};

/**
 * Check if the document is fully loaded.
 * @returns {boolean|boolean}
 */
__pulsar_utils__.isFullyLoaded = function() {
    return this.isActuallyReady();
};

/**
 * Check if the document is fully loaded and ready to analyze.
 * A document is hardly be perfect ready in time, since it's very common there are very slow sub resources to wait for.
 * */
__pulsar_utils__.isActuallyReady = function() {
    // unexpected
    if (!document.body) {
        return false
    }

    this.__updateStat();

    if (!__pulsar_utils__.data) {
        return false
    }

    let ready = false;
    let trace = __pulsar_utils__.data.trace;
    let status = trace.status;
    let d = trace.lastD;

    // all sub resources are loaded, the document is ready now
    if (status.st === "c") {
        // assert(document.readyState === "complete")
        status.r = "st";
        ready = true
    }

    // The DOM is very good for analysis, no wait for more information
    let stat = trace.lastStat;
    if (status.n > 20 && stat.h >= this.fineHeight
        && stat.na >= this.fineNumAnchor
        && stat.ni >= this.fineNumImage
    ) {
        if (d.h < 10 && d.na === 0 && d.ni === 0 && d.nst === 0 && d.nnm === 0) {
            // DOM changed since last check, store the latest stat and return false to wait for the next check
            ++status.idl;
            if (status.idl > 10) {
                // idle for 10 seconds
                status.r = "ct";
                ready = true;
            }
        }
    }

    return ready;
};

__pulsar_utils__.isIdle = function() {
    let idle = false;
    let trace = __pulsar_utils__.data.trace;
    let status = trace.status;
    let d = trace.lastD;
    if (d.h < 10 && d.na === 0 && d.ni === 0 && d.nst === 0 && d.nnm === 0) {
        // DOM changed since last check, store the latest stat and return false to wait for the next check
        ++status.idl;
        if (status.idl > 5) {
            // idle for 5 seconds
            idle = true;
        }
    }
    return idle
};

/**
 * @return {Object}
 * */
__pulsar_utils__.__updateStat = function(init = false) {
    if (!document.body) {
        return
    }

    const config = this.getConfig();
    const viewPortWidth = config.viewPortWidth;

    // Width/height need to reflect the full page, but also must be robust:
    // some pages can report pathological sizes (infinite/huge due to bad CSS/JS).
    // We cap sizes to keep stats stable and avoid downstream overflows.
    const maxWidth = Math.max(1, 1.2 * viewPortWidth);
    const maxHeight = 150000; // 150k px is far beyond typical pages but prevents runaway values

    let width = 0;
    let height = 0;
    let na = 0;  // anchor
    let ni = 0;  // image
    let nst = 0; // short text in first screen
    let nnm = 0; // number like text in first screen

    if (!this.isBrowserError()) {
        NodeOps.forEach(document.body, (node) => {
            // 2023.08: google sites complains that node.__pulsar_isIFrame is not defined sometimes
            // We only want to skip iframe subtrees.
            if (NodeOps.isIFrame(node)) {
                return;
            }

            if (NodeOps.isAnchor(node)) ++na;
            if (NodeOps.isImage(node) && !NodeOps.isSmallImage(node)) ++ni;

            if (NodeOps.isText(node) && NodeOps.nScreen(node) <= 20) {
                let isShortText = NodeOps.isShortText(node);
                let isNumberLike = isShortText && NodeOps.isNumberLike(node);
                if (isShortText) {
                    ++nst;
                    if (isNumberLike) {
                        ++nnm;
                    }

                    let ele = NodeOps.bestElement(node);
                    if (ele != null && !init && !ele.hasAttribute("tp")) {
                        // not set at initialization, it's lazy loaded.
                        // "lz" is short for lazy.
                        // TODO: embed all pulsar generated data into a single attribute to reduce the page size
                        ele.setAttribute("lz", "1")
                    }

                    if (ele != null) {
                        let type = isNumberLike ? "nm" : "st";
                        // "tp" is short for type.
                        ele.setAttribute("tp", type);
                    }
                }
            }

            // Requirement: width/height are the maxima across *all* elements on the page.
            // Use scroll sizes to reflect the full layout; fall back to offset/client.
            // Add sanity checks to avoid skew from accidental huge/Infinity/NaN values.
            if (node && node.nodeType === 1) {
                let w;
                let h;

                try {
                    w = Math.max(node.scrollWidth || 0, node.offsetWidth || 0, node.clientWidth || 0);
                    h = Math.max(node.scrollHeight || 0, node.offsetHeight || 0, node.clientHeight || 0);
                } catch (e) {
                    w = 0;
                    h = 0;
                }

                if (!Number.isFinite(w) || w < 0) w = 0;
                if (!Number.isFinite(h) || h < 0) h = 0;

                // cap extreme values
                if (w > maxWidth) w = maxWidth;
                if (h > maxHeight) h = maxHeight;

                if (w > width) {
                    width = w;
                }
                if (h > height) {
                    height = h;
                }
            }
        });

        // Fallback: ensure at least the document's own sizes are considered.
        try {
            const de = document.documentElement;
            if (de) {
                let dw = Math.max(de.scrollWidth || 0, de.clientWidth || 0);
                let dh = Math.max(de.scrollHeight || 0, de.clientHeight || 0);
                if (!Number.isFinite(dw) || dw < 0) dw = 0;
                if (!Number.isFinite(dh) || dh < 0) dh = 0;
                if (dw > maxWidth) dw = maxWidth;
                if (dh > maxHeight) dh = maxHeight;
                width = Math.max(width, dw);
                height = Math.max(height, dh);
            }
            if (document.body) {
                let bw = Math.max(document.body.scrollWidth || 0, document.body.clientWidth || 0);
                let bh = Math.max(document.body.scrollHeight || 0, document.body.clientHeight || 0);
                if (!Number.isFinite(bw) || bw < 0) bw = 0;
                if (!Number.isFinite(bh) || bh < 0) bh = 0;
                if (bw > maxWidth) bw = maxWidth;
                if (bh > maxHeight) bh = maxHeight;
                width = Math.max(width, bw);
                height = Math.max(height, bh);
            }
        } catch (e) {
            // ignore
        }
    }

    // unexpected but occurs when do performance test to parallel harvest Websites
    if (!__pulsar_utils__.data) {
        return
    }

    let trace = __pulsar_utils__.data.trace;
    let initStat = trace.initStat;
    if (!initStat) {
        initStat = { w: width, h: height, na: na, ni: ni, nst: nst, nnm: nnm };
        trace.initStat = initStat
    }
    let lastStat = trace.lastStat;
    let lastStatus = trace.status;
    let state = document.readyState.substr(0, 1);
    let newMultiStatus = {
        status: {n: lastStatus.n, scroll: lastStatus.scroll, idl: lastStatus.idl, st: state, r: lastStatus.r},
        lastStat: {w: width, h: height, na: na, ni: ni, nst: nst, nnm: nnm},
        // changes from last round
        lastD: {
            w: width - lastStat.w,
            h: height - lastStat.h,
            na: na - lastStat.na,
            ni: ni - lastStat.ni,
            nst: nst - lastStat.nst,
            nnm: nnm - lastStat.nnm
        },
        // changes from the initialization
        initD: {
            w: width - initStat.w,
            h: height - initStat.h,
            na: na - initStat.na,
            ni: ni - initStat.ni,
            nst: nst - initStat.nst,
            nnm: nnm - initStat.nnm
        }
    };

    __pulsar_utils__.data.trace = Object.assign(trace, newMultiStatus)

    return __pulsar_utils__.data
};

/**
 * @param {Number} ratio The ratio of the page's height to scroll to, default is 0.5
 * */
__pulsar_utils__.scrollToMiddle = function(ratio = 0.5) {
    if (!document || !document.documentElement || !document.body) {
        return
    }

    if (ratio < 0 || ratio > 1) {
        ratio = 0.5
    }

    let x = 0;
    let y = Math.max(
        document.documentElement.scrollHeight,
        document.documentElement.clientHeight,
        document.body.scrollHeight
    );
    y = Math.min(y, 15000) * ratio

    window.scrollTo(x, y)
};

/**
 * @param {Number} screenNumber The ratio of the page's height to scroll to, default is 1.0
 * */
__pulsar_utils__.scrollToScreen = function(screenNumber = 1.0) {
    return __pulsar_utils__.scrollToViewport(screenNumber)
}

/**
 * Scroll the page to the start of the n-th viewport (0-based index).
 * n = 0  → scroll to top (0)
 * n = 1  → scroll to one viewport height
 * @param {number} n The viewport index to scroll to (0-based)
 */
__pulsar_utils__.scrollToViewport = function (n = 0) {
    if (!document?.documentElement || !document?.body) return;

    const config = this.getConfig?.() || {};
    const viewportHeight = config.viewPortHeight || window.innerHeight;

    const totalHeight = Math.min(
        Math.max(
            document.documentElement.scrollHeight,
            document.body.scrollHeight
        ),
        15000
    );

    // 0-based: first viewport = 0px
    const y = Math.min(totalHeight, n * viewportHeight);
    window.scrollTo(0, y);
};

/**
 * @deprecated using BrowserProtocol instead
 * */
__pulsar_utils__.scrollToBottom = function() {
    if (!document || !document.documentElement || !document.body) {
        return
    }

    let x = 0;
    let y = Math.max(
        document.documentElement.scrollHeight,
        document.documentElement.clientHeight,
        document.body.scrollHeight
    );
    y = Math.min(y, 15000)

    window.scrollTo(x, y)
};

/**
 * @deprecated using BrowserProtocol instead
 * */
__pulsar_utils__.scrollUp = function() {
    if (!__pulsar_utils__.data) {
        // TODO: this occurs when do performance test, but the reason is not investigated
        // return false
    }

    window.scrollBy(0, -500);
};

/**
 * @deprecated using BrowserProtocol instead
 * */
__pulsar_utils__.scrollToTop = function() {
    window.scrollTo(0, 0)
};

/**
 * @deprecated using BrowserProtocol instead
 * */
__pulsar_utils__.scrollDown = function() {
    window.scrollBy(0, 500);
};

__pulsar_utils__.scrollDownN = function(scrollCount = 5) {
    if (!__pulsar_utils__.data) {
        // TODO: this occurs when do performance test, but the reason is not investigated
        // return false
    }

    let status = __pulsar_utils__.data.trace.status;

    window.scrollBy(0, 500);
    status.scroll += 1;

    return status.scroll >= scrollCount
};

/**
 * Check if a element be visible
 *
 * @param  {String} selector
 * @return boolean
 * @deprecated use BrowserProtocol instead
 */
__pulsar_utils__.isVisible = function(selector) {
    let ele = document.querySelector(selector)
    if (ele == null) {
        return false
    }
    return this.isElementVisible(ele)
}

/**
 * Check if a element be visible.
 *
 * @param  {Element} element
 * @return boolean
 */
__pulsar_utils__.isElementVisible = function(element) {
    if (!element.ownerDocument || !element.ownerDocument.defaultView)
        return true;

    const style = element.ownerDocument.defaultView.getComputedStyle(element);
    if (!style || style.visibility === 'hidden')
        return false;
    if (style.display === 'contents') {
        // display:contents is not rendered itself, but its child nodes are.
        for (let child = element.firstChild; child; child = child.nextSibling) {
            if (child.nodeType === 1 /* Node.ELEMENT_NODE */ && this.isElementVisible(child)) {
                return true;
            }
            if (child.nodeType === 3 /* Node.TEXT_NODE */ && this.isVisibleTextNode(child)) {
                return true;
            }
        }
        return false;
    }
    const rect = element.getBoundingClientRect();
    return rect.width > 0 && rect.height > 0;
}

/**
 * Check if a text node be visible.
 *
 * @param  {Node} node
 * @return boolean
 */
__pulsar_utils__.isVisibleTextNode = function (node) {
    // https://stackoverflow.com/questions/1461059/is-there-an-equivalent-to-getboundingclientrect-for-text-nodes
    const range = document.createRange();
    range.selectNode(node);
    const rect = range.getBoundingClientRect();
    return rect.width > 0 && rect.height > 0;
}

__pulsar_utils__.getVisibleTextContent = function() {
    const elements = document.body.querySelectorAll('*');
    const visibleTexts = [];

    // new __pulsar_NodeTraversor(new __pulsar_NodeFeatureCalculator()).traverse(document.body);

    elements.forEach(el => {
        const rect = el.getBoundingClientRect();
        const isVisible =
            rect.width > 0 &&
            rect.height > 0 &&
            rect.bottom >= 0 &&
            rect.right >= 0 &&
            rect.top <= (window.innerHeight || document.documentElement.clientHeight) &&
            rect.left <= (window.innerWidth || document.documentElement.clientWidth);

        const style = window.getComputedStyle(el);
        const isDisplayed = style.display !== 'none' && style.visibility !== 'hidden' && style.opacity !== '0';

        if (isVisible && isDisplayed && el.childElementCount === 0 && el.textContent.trim()) {
            visibleTexts.push(el.textContent.trim());
        }
    });

    return visibleTexts;
}

/**
 * Test if a element is checked.
 *
 * @param  {String} selector
 * @return boolean
 */
__pulsar_utils__.isChecked = function(selector) {
    let ele = document.querySelector(selector)
    if (ele == null) {
        return false
    }
    return this.isElementChecked(ele, false)
}

/**
 * 检查一个元素是否处于“选中”状态。
 * 支持：
 *  - 原生 <input type="checkbox|radio">
 *  - 自定义控件 (role="checkbox|radio" + aria-checked)
 *
 * @param {Element} element 要检查的 DOM 元素
 * @param {boolean} [strict=true] 是否严格模式（默认为 true）
 * @returns {boolean|string} true / false / "mixed"
 */
__pulsar_utils__.isElementChecked = function(element, strict = true) {
    if (!element) {
        if (strict) throw this.createStacklessError('Element is null or undefined');
        return false;
    }

    // 1️⃣ 处理 ARIA 自定义控件
    const role = element.getAttribute('role');
    if (role && ['checkbox', 'radio'].includes(role.toLowerCase())) {
        const state = element.getAttribute('aria-checked');
        if (state === 'mixed') return 'mixed';
        return state === 'true';
    }

    // 2️⃣ 处理原生控件
    if (element instanceof HTMLInputElement &&
        ['checkbox', 'radio'].includes(element.type.toLowerCase())) {
        return element.checked;
    }

    // 3️⃣ 其他情况
    if (strict) {
        throw this.createStacklessError('Not a checkbox or radio button');
    } else {
        return false;
    }
};

/**
 * Scroll into view.
 *
 * @param {String} selector The element to scroll to
 * @param {Object} [options] Optional scroll options to override defaults
 * @deprecated use BrowserProtocol instead
 * */
__pulsar_utils__.scrollIntoView = function(selector, options) {
    try {
        const el = document.querySelector(selector);
        if (!el) return false;

        // Determine if scrolling is actually needed
        const rect = el.getBoundingClientRect();
        const vw = window.innerWidth || document.documentElement.clientWidth;
        const vh = window.innerHeight || document.documentElement.clientHeight;
        const fullyInView = rect.top >= 0 && rect.left >= 0 && rect.bottom <= vh && rect.right <= vw;

        if (!fullyInView) {
            const opts = Object.assign({
                behavior: 'smooth',
                block: 'center',
                inline: 'nearest'
            }, options || {});
            el.scrollIntoView(opts);
            return true;
        }
        return false;
    } catch (e) {
        // Fallback: best-effort immediate scroll to avoid breaking flows
        try {
            const el = document.querySelector(selector);
            if (el) {
                el.scrollIntoView({ behavior: 'auto', block: 'start', inline: 'nearest' });
                return true;
            }
        } catch (_) { /* ignore */ }
        return false;
    }
};

/**
 * Select the first element and click it
 *
 * @param  {String} selector
 * @return
 * @deprecated use BrowserProtocol instead
 */
__pulsar_utils__.click = function(selector) {
    let ele = document.querySelector(selector)
    if (ele instanceof HTMLElement) {
        ele.click()
    }
}

/**
 * Select the first element and click it.
 *
 * @param  {String} selector
 * @param  {String} pattern
 * @return
 */
__pulsar_utils__.clickTextMatches = function(selector, pattern) {
    // TODO: handle selector `*`

    let elements = document.querySelectorAll(selector)
    for (let ele of elements) {
        if (ele instanceof HTMLElement) {
            let text = ele.textContent
            if (text.match(pattern)) {
                ele.scrollIntoView()
                ele.click()
            }
        }
    }
}

/**
 * Select the first element and click it.
 *
 * @param  {number} n The n-th anchor.
 * @param  {string|null} rootSelector The n-th anchor.
 * @return {string|null}
 */
__pulsar_utils__.clickNthAnchor = function(n, rootSelector) {
    let rootNode
    if (!rootSelector) {
        rootNode = document.body
    } else {
        rootNode = document.querySelector(rootSelector)
    }

    if (!rootNode) {
        return null
    }

    let c = 0
    let href = null

    __pulsar_TreeWalker.forEachElement(rootNode, function (node) {
        if (NodeOps.isAnchor(node) && NodeOps.maybeClickable(node)) {
            ++c;
            if (c === n) {
                node.scrollIntoView()
                href = node.getAttribute("href")
                node.click()
            }
        }
    });

    return href
}

/**
 * Select the first element and check it if not checked.
 *
 * @param  {String} selector
 * @return
 */
__pulsar_utils__.check = function(selector) {
    if (!this.isChecked(selector)) {
        let ele = document.querySelector(selector)
        if (ele instanceof HTMLElement) {
            ele.click()
        }
    }
}

/**
 * Select the first element and uncheck it if checked.
 *
 * @param  {String} selector
 * @return
 */
__pulsar_utils__.uncheck = function(selector) {
    if (this.isChecked(selector)) {
        let ele = document.querySelector(selector)
        if (ele instanceof HTMLElement) {
            ele.click()
        }
    }
}

/**
 * Select the first element and extract the text
 *
 * @param  {String} selector
 * @return {String}
 * @deprecated use BrowserProtocol instead
 */
__pulsar_utils__.outerHTML = function(selector) {
    let element = document.querySelector(selector)
    if (element != null) {
        return element.outerHTML
    }
    return null
};

/**
 * Select the first element and extract the text
 *
 * @param  {String} selector
 * @return {String|null}
 */
__pulsar_utils__.selectFirstText = function(selector) {
    let element = document.querySelector(selector)
    if (element != null) {
        return element.textContent
    }
    return null
};

/**
 * @deprecated Use selectTextAll instead
 */
__pulsar_utils__.allTexts = function(selector) {
    return __pulsar_utils__.selectTextAll(selector)
};

/**
 * Select elements and extract the texts
 *
 * @param  {String} selector
 * @return {String} texts in json format
 */
__pulsar_utils__.selectTextAll = function(selector) {
    let elements = document.querySelectorAll(selector)
    let texts = Array.from(elements).map(e => e.textContent)
    return JSON.stringify(texts, null, 2)
};
















/**
 * Select the first element and extract the text
 *
 * @param  {String} selector
 * @param  {String} attrName
 * @return {String|null}
 */
__pulsar_utils__.selectFirstAttribute = function(selector, attrName) {
    let element = document.querySelector(selector)
    if (element != null) {
        return element.getAttribute(attrName)
    }
    return null
};

/**
 * Select the first matching element and extract all the attributes.
 *
 * @param  {String} selector
 * @return {Object} attribute values
 * */
__pulsar_utils__.selectAttributes = function(selector) {
    let element = document.querySelector(selector)
    if (element != null) {
        // return JSON.stringify(attrs, null, 2)
        return Array.from(element.attributes)
            .flatMap(a => [a.name, a.value])
    }
    return []
};

/**
 * Select all the matching elements and extract the attribute with given name.
 *
 * @param  {String} selector
 * @param  {String} attrName
 * @param  {Number} start The beginning index of the specified portion of the array.
 * If start is undefined, then the slice begins at index 0.
 * @param  {Number} end The end index of the specified portion of the array. This is exclusive of the element at the index 'end'.
 * If end is undefined, then the slice extends to the end of the array.
 * @return {string} attribute values in json format
 */
__pulsar_utils__.selectAttributeAll = function(selector, attrName, start, end) {
    let elements = document.querySelectorAll(selector)
    let values = Array.from(elements)
        .map(e => e.getAttribute(attrName))
        .filter(v => v != null)
    if (start || end) {
        values = values.slice(start, end)
    }
    return JSON.stringify(values, null, 2)
};

/**
 * Select elements and extract the texts
 *
 * @param {String} selector
 * @param {String} attrName
 * @param {String} attrValue
 */
__pulsar_utils__.setAttribute = function(selector, attrName, attrValue) {
    let element = document.querySelector(selector)
    if (element != null) {
        element.setAttribute(attrName, attrValue)
    }
};

/**
 * Select elements and extract the texts
 *
 * @param {String} selector
 * @param {String} attrName
 * @param {String} attrValue
 */
__pulsar_utils__.setAttributeAll = function(selector, attrName, attrValue) {
    let elements = document.querySelectorAll(selector)
    elements.forEach(e => e.setAttribute(attrName, attrValue))
};
















/**
 * Select the first element and retrieve the property value
 *
 * @param  {String} selector
 * @param  {String} propName
 * @return {String|null}
 */
__pulsar_utils__.selectFirstPropertyValue = function(selector, propName) {
    let element = document.querySelector(selector)
    if (element != null) {
        return element[propName]
    }
    return null
};

/**
 * Select all the matching elements and extract the property value with given name.
 *
 * @param  {String} selector
 * @param  {String} propName
 * @param  {Number} start The beginning index of the specified portion of the array.
 * If start is undefined, then the slice begins at index 0.
 * @param  {Number} end The end index of the specified portion of the array. This is exclusive of the element at the index 'end'.
 * If end is undefined, then the slice extends to the end of the array.
 * @return {string} property values in json format
 */
__pulsar_utils__.selectPropertyValueAll = function(selector, propName, start, end) {
    let elements = document.querySelectorAll(selector)
    let values = Array.from(elements)
        .map(e => e[propName])
        .filter(v => v != null)
    if (start || end) {
        values = values.slice(start, end)
    }
    return JSON.stringify(values, null, 2)
};

/**
 * Select elements and set the property value
 *
 * @param {String} selector
 * @param {String} propName
 * @param {String} propValue
 */
__pulsar_utils__.setProperty = function(selector, propName, propValue) {
    let element = document.querySelector(selector)
    if (element != null) {
        element[propName] = propValue
    }
};

/**
 * Select elements and set the property value
 *
 * @param {String} selector
 * @param {String} propName
 * @param {String} propValue
 */
__pulsar_utils__.setPropertyAll = function(selector, propName, propValue) {
    let elements = document.querySelectorAll(selector)
    elements.forEach(e => e[propName] = propValue)
};



































/**
 * Select the first anchor element and extract the link.
 *
 * @param  {String} selector
 * @return {String|null}
 */
__pulsar_utils__.selectFirstHyperlink = function(selector) {
    let element = document.querySelector(selector)
    if (element != null && element.nodeName === 'A') {
        return element.href
    }
    return null
};

/**
 * Select all anchor elements and extract all the links.
 *
 * @param  {String} selector
 * @return {String} links separated by line break "\n"
 */
__pulsar_utils__.selectHyperlinks = function(selector) {
    let elements = document.querySelectorAll(selector)
    return Array.from(elements).filter(e => e.nodeName === 'A').map(e => e.href).join("\n")
};

/**
 * Select all img elements and extract all the links.
 *
 * @param  {String} selector
 * @return {String} links separated by line break "\n"
 */
__pulsar_utils__.selectImages = function(selector) {
    let elements = document.querySelectorAll(selector)
    return Array.from(elements).filter(e => e.nodeName === 'IMG').map(e => e.src).join("\n")
};

/**
 * Select elements and extract the texts
 *
 * @param  {string} pattern
 * @param  {string} frameNameOrId
 * @return {string|null}
 */
__pulsar_utils__.findMatches = function(pattern, frameNameOrId) {
    let expression = `(//frame|//iframe)[@name="${frameNameOrId}" or @id="${frameNameOrId}"]`
    let frameContext = document.evaluate(expression, document,null,
        XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null
    ).snapshotItem(0).contentDocument;
    let element = frameContext.__pulsar_findMatches(pattern)
    return element?.textContent
};

/**
 * Select elements and extract the texts
 *
 * @param  {String} selector
 * @param  {String} attrName
 * @return {Array}
 */
__pulsar_utils__.findMatchesForAttrs = function(selector, attrName) {
    let elements = document.querySelectorAll(selector)
    return elements.map(e => e.getAttribute(attrName))
};

/**
 * Select elements and extract the texts
 *
 * @param  {string} selector
 * @param  {string} attrName
 * @return {any}
 */
__pulsar_utils__.doForAllFrames = function(selector, attrName) {
    this.__doForAllFramesRecursively(window, 0, selector, attrName)
    return "hello"
};

/**
 * Select elements and extract the texts.
 *
 * @param  {Window} rootFrame
 * @param depth {number}
 * @param  {string} selector
 * @param  {string} attrName
 * @return {any}
 */
__pulsar_utils__.__doForAllFramesRecursively = function(rootFrame, depth, selector, attrName) {
    let doc = rootFrame.document
    doc.body.style.background = "green";
    doc.body.setAttribute("data-user", "vincent")
    doc.body.setAttribute("data-depth", depth.toString())
    doc.body.setAttribute("data-frames", rootFrame.frames.length.toString())

    console.log(rootFrame.name)

    // doc.body.__pulsar_forEachElement(e => {
    //     let textContent = e.textContent
    //     if (textContent.contains("PRESS")) {
    //         // e.textContent = "PRESSED"
    //     }
    // })

    let dep = window.document.body.getAttribute("data-depth") || 0
    if (depth > dep) {
        window.document.body.setAttribute("data-depth", depth.toString())
    }

    const frames = rootFrame.frames; // or const frames = window.parent.frames;
    for (let i = 0; i < frames.length; i++) {
        // do something with each subframe as frames[i]
        let frame = frames[i]

        this.__doForAllFramesRecursively(frame, depth + 1, selector, attrName)
    }

    return frames.length
};

/**
 * Clones an object.
 *
 * @param  {Object} o
 * @return {Object}
 */
__pulsar_utils__.clone = function(o) {
    return JSON.parse(JSON.stringify(o))
};

/**
 * Get attribute as an integer
 * @param node {Element}
 * @param attrName {String}
 * @param defaultValue {Number}
 * @return {Number}
 * */
__pulsar_utils__.getIntAttribute = function(node, attrName, defaultValue) {
    if (!defaultValue) {
        defaultValue = 0;
    }

    let value = node.getAttribute(attrName);
    if (!value) {
        return defaultValue;
    }

    return parseInt(value);
};

/**
 * Increase the attribute value as if it's an integer
 * @param node {Element}
 * @param attrName {String}
 * @param add {Number}
 * */
__pulsar_utils__.increaseIntAttribute = function(node, attrName, add) {
    let value = node.getAttribute(attrName);
    if (!value) {
        value = '0';
    }

    value = parseInt(value) + add;
    node.setAttribute(attrName, value.toString())
};

/**
 * Get attribute as an integer
 * */
__pulsar_utils__.getReadableNodeName = function(node) {
    let name = node.tagName
        + (node.id ? ("#" + node.id) : "")
        + (node.className ? ("#" + node.className) : "");

    let seq = this.getIntAttribute(node, "_seq", -1);
    if (seq >= 0) {
        name += "-" + seq;
    }

    return name;
};

/**
 * Serialize the document (or a subtree) into an HTML string, injecting
 * visual-information attributes (vi, _h, _oh, tv0, tv1, ...) from the
 * _viDataMap WeakMap without mutating the live DOM.
 *
 * @param root {Node} defaults to document.documentElement
 * @param metaLinks {Object} optional map of rel -> href for <link> elements
 *   to inject into <head> during serialization (no DOM mutation).
 * @return {string} The annotated HTML string
 */
__pulsar_utils__.serializeAnnotatedHTML = function(root, metaLinks) {
    const viMap = this._viDataMap;
    const config = this.getConfig();
    const VOID = new Set([
        'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
        'link', 'meta', 'param', 'source', 'track', 'wbr'
    ]);

    function escAttr(s) {
        return String(s).replace(/[&"<>]/g, function(c) {
            return ({'&': '&amp;', '"': '&quot;', '<': '&lt;', '>': '&gt;'})[c];
        });
    }
    function escText(s) {
        return String(s).replace(/[&<>]/g, function(c) {
            return ({'&': '&amp;', '<': '&lt;', '>': '&gt;'})[c];
        });
    }

    var html = '';

    function serializeNode(node) {
        if (node.nodeType === Node.TEXT_NODE) {
            html += escText(node.textContent);
            return;
        }
        if (node.nodeType === Node.COMMENT_NODE) {
            html += '<!--' + node.textContent + '-->';
            return;
        }
        if (node.nodeType !== Node.ELEMENT_NODE) return;

        // For non-HTML namespaced elements (SVG, MathML, etc.), fall back to
        // native outerHTML which handles namespaces and case-sensitive tag names
        // correctly.  vi data is never computed for these elements.
        if (node.namespaceURI && node.namespaceURI !== 'http://www.w3.org/1999/xhtml') {
            html += node.outerHTML;
            return;
        }

        var tag = node.tagName.toLowerCase();
        html += '<' + tag;

        // Emit existing attributes
        var attrs = node.attributes;
        for (var i = 0; i < attrs.length; i++) {
            var attr = attrs[i];
            html += ' ' + attr.name + '="' + escAttr(attr.value) + '"';
        }

        // Inject vi attributes from WeakMap (no DOM mutation)
        var data = viMap ? viMap.get(node) : null;
        if (data) {
            if (data.vi) {
                html += ' ' + config.ATTR_ELEMENT_NODE_VI + '="' + data.vi + '"';
            }
            if (data.elementData) {
                html += ' ' + config.ATTR_ELEMENT_NODE_DATA + '="' + data.elementData + '"';
            }
            if (data.hidden) {
                html += ' ' + data.hidden.attrName + '="1"';
            }
            if (data.overflowHidden) {
                html += ' ' + config.ATTR_OVERFLOW_HIDDEN + '="1"';
            }
            if (data.textNodeRects) {
                for (var j = 0; j < data.textNodeRects.length; j++) {
                    var tv = data.textNodeRects[j];
                    if (tv) {
                        html += ' ' + config.ATTR_TEXT_NODE_VI + j + '="' + tv + '"';
                    }
                }
            }
        }

        // Void elements have no children and no closing tag
        if (VOID.has(tag)) {
            html += '>';
            return;
        }

        html += '>';
        for (var child = node.firstChild; child; child = child.nextSibling) {
            serializeNode(child);
        }

        // Inject capture meta links into <head> during serialization.
        // This avoids DOM mutation — the links appear only in the output,
        // not in the live page.
        if (tag === 'head' && metaLinks) {
            var rels = Object.keys(metaLinks);
            for (var li = 0; li < rels.length; li++) {
                var rel = rels[li];
                var href = metaLinks[rel];
                html += '<link rel="' + escAttr(rel) + '" href="' + escAttr(href) + '" />';
            }
        }

        html += '</' + tag + '>';
    }

    serializeNode(root || document.documentElement);
    return html;
};

/**
 * Get the annotated HTML with vi attributes injected during serialization.
 * Falls back to native outerHTML when no vi data has been computed
 * (e.g., content-length estimation before compute() is called).
 *
 * @return {string} The annotated HTML string
 */
__pulsar_utils__.getAnnotatedHTML = function() {
    if (!this._viDataComputed || !this._viDataMap) {
        return document.documentElement.outerHTML;
    }
    return this.serializeAnnotatedHTML(document.documentElement, this._captureMetaLinks);
};

/**
 * Get the annotated HTML for a specific element matched by selector,
 * with vi attributes injected during serialization.
 * Falls back to native outerHTML when no vi data has been computed.
 *
 * @param selector {string} CSS selector for the target element
 * @return {string|null} The annotated HTML string, or null if no element matches
 */
__pulsar_utils__.getAnnotatedOuterHTML = function(selector) {
    var el = document.querySelector(selector);
    if (!el) return null;
    if (!this._viDataComputed || !this._viDataMap) {
        return el.outerHTML;
    }
    return this.serializeAnnotatedHTML(el);
};

/**
 * Add to attribute
 *
 * @param node {Node|Element|Text}
 * @param attributeName {String}
 * @param key {String}
 * @param value {Object}
 * */
__pulsar_utils__.addTuple = function(node, attributeName, key, value) {
    let attributeValue = node.getAttribute(attributeName) || "";
    if (attributeValue.length > 0) {
        attributeValue += " "
    }
    attributeValue += key + ":" + value.toString();
    node.setAttribute(attributeName, attributeValue);
};

/**
 * The full page metrics
 * */
__pulsar_utils__.getFullPageMetrics = function() {
    let metrics = {
        width: Math.max(window.innerWidth, document.body.scrollWidth, document.documentElement.scrollWidth) | 0,
        height: Math.max(window.innerHeight, document.body.scrollHeight, document.documentElement.scrollHeight) | 0,
        deviceScaleFactor: window.devicePixelRatio || 1,
        mobile: typeof window.orientation !== 'undefined'
    };

    return JSON.stringify(metrics)
};

/**
 * Create an info box in pure JavaScript to show information for the element with the selector.
 * The info box appears in the top right corner of the element.
 * The information includes the tag name, id, class, and the text content.
 *
 * @param selector {String} The selector to get the element from.
 */
__pulsar_utils__.showInfoBox = function(selector) {
    let element = document.querySelector(selector)
    if (element != null) {
        let tagName = element.tagName
        let id = element.id
        let classes = element.className
        let textContent = element.textContent

        let infoBox = document.createElement("div")
        infoBox.style.position = "absolute"
        infoBox.style.top = (element.offsetTop - 10) + "px"
        infoBox.style.right = (element.offsetLeft + element.offsetWidth + 10) + "px"
        infoBox.style.backgroundColor = "rgba(255, 255, 255, 0.8)"
        infoBox.style.padding = "10px";
        infoBox.style.border = "1px solid #ccc";
        infoBox.style.borderRadius = "4px";
        infoBox.style.boxShadow = "0 2px 8px rgba(0, 0, 0, 0.1)";
        infoBox.style.zIndex = "1000";  // Ensuring it appears on top

        let title = document.createElement("h2");
        title.textContent = "Element Info";
        title.style.margin = "0 0 10px 0";
        title.style.fontSize = "16px";
        infoBox.appendChild(title);

        let infoBody = document.createElement("div");
        infoBox.appendChild(infoBody);
        infoBody.innerHTML = `
            <p><b>Tag Name:</b> ${tagName}</p>
            <p><b>ID:</b> ${id}</p>
            <p><b>Classes:</b> ${classes}</p>
            <p><b>Text Content:</b> ${textContent}</p>
        `;

        document.body.appendChild(infoBox);  // Append the infoBox to the body
    } else {
        console.error("Element with selector $selector not found.")
    }
}

/**
 * Compute the final metadata, the metadata is stored in the __pulsar_utils__.data.metadata
 * */
__pulsar_utils__.computeMetadata = function() {
    let config = __pulsar_utils__.getConfig();
    console.assert(config != null, "config is null")

    let dateTime = new Date().toLocaleDateString() + " " + new Date().toLocaleTimeString()
    let timestamp = new Date().getTime().toString()
    // TODO: check the standard and understand the extract meaning of these parameters
    let scrollTop = document.documentElement.scrollTop || document.body.scrollTop
    let scrollLeft = document.documentElement.scrollLeft || document.body.scrollLeft
    let clientWidth = window.innerWidth || document.documentElement.clientWidth
    let clientHeight = window.innerHeight || document.documentElement.clientHeight
    // 0.00 means at the top of the first screen, 1.50 means halfway through the second screen.
    const screenNumber = window.scrollY / window.innerHeight;

    let metadata = {};

    metadata["viewPortWidth"] = config.viewPortWidth
    metadata["viewPortHeight"] = config.viewPortHeight
    metadata["scrollTop"] = scrollTop.toFixed(2)
    metadata["scrollLeft"] = scrollLeft.toFixed(2)
    metadata["clientWidth"] = clientWidth.toFixed(2)
    metadata["clientHeight"] = clientHeight.toFixed(2)

    metadata["screenNumber"] = screenNumber.toFixed(2)

    metadata["dateTime"] = dateTime
    metadata["timestamp"] = timestamp

    return metadata
}

/**
 * Generate meta data
 * TODO: do not modify the DOM
 * */
__pulsar_utils__.generateMetadata = function() {
    const config = this.getConfig();
    let meta = document.getElementById(config.META_INFORMATION_ID);
    if (meta != null) {
        // already generated
        return
    }

    let domain = document.domain
    let viewPort = config.viewPortWidth + "x" + config.viewPortHeight
    let dateTime = new Date().toLocaleDateString() + " " + new Date().toLocaleTimeString()
    let timestamp = new Date().getTime().toString()

    let ele = document.createElement("input");
    ele.setAttribute("type", "hidden");
    ele.setAttribute("id", config.META_INFORMATION_ID);
    ele.setAttribute("domain", domain);
    ele.setAttribute("view-port", viewPort);
    ele.setAttribute("date-time", dateTime);
    ele.setAttribute("timestamp", timestamp);

    document.body.appendChild(ele);
};

/**
 * Calculate visualization info and do human actions
 * */
__pulsar_utils__.compute = function() {
    if (!document.body || !document.body.firstChild) {
        return
    }

    // Ensure data exists even if compute() is called without a prior checkStatus() call.
    this.createDataIfAbsent();

    const DATA_ERROR = "data-error";

    let done = document.body.hasAttribute(DATA_ERROR);
    if (done) {
        return
    }

    __pulsar_utils__.data.metadata = this.computeMetadata();

    window.scrollTo(0, 0);

    // calling window.stop will pause all resource loading
    window.stop();

    this.__updateStat();

    // TODO: do not inject any data into the DOM
    this.writeData();

    // remove temporary flags
    NodeOps.forEachElement(document.body, ele => {
        ele.removeAttribute("tp")
    });

    // Initialize the WeakMap that stores computed visual information (vi, _h, _oh, tvN)
    // without polluting the live DOM.  NodeFeatureCalculator writes to this map instead
    // of calling setAttribute.  The data is later injected into the captured HTML by
    // serializeAnnotatedHTML().
    this._viDataMap = new WeakMap();
    this._viDataComputed = false;

    // traverse the DOM and compute necessary data, we must compute data before we perform humanization
    let calculator = new __pulsar_NodeFeatureCalculator();
    __pulsar_TreeWalker.traverseWithHeadTail(
        document.body,
        function(node, depth) { calculator.head(node, depth); },
        function(node, depth) { calculator.tail(node, depth); },
        calculator
    );

    // Flag that vi data is available for getAnnotatedHTML()
    this._viDataComputed = true;

    this.generateMetadata();

    this.addProjectSpecifiedData();

    // if any script error occurs, the flag can NOT be seen
    // TODO: do not inject any data into the DOM
    document.body.setAttribute(DATA_ERROR, '0');

    return this.getActiveDomMessage()
};

__pulsar_utils__.addProjectSpecifiedData = function() {

};

/**
 * Get the active DOM message which is the current state of the DOM.
 * The active DOM message is the JSON string of the __pulsar_utils__.data.
 * It's computed in updateStat(), and computeFinalMetadata()
 * */
__pulsar_utils__.getActiveDomMessage = function() {
    return JSON.stringify(__pulsar_utils__.data)
};

/**
 * Create a error without stack trace
 *
 * @param {String} message
 * @return {Error}
 * */
__pulsar_utils__.createStacklessError = function (message) {
    const error = new Error(message);
    // Chromium/WebKit should delete the stack instead.
    delete error.stack;
    return error;
}

/**
 * Return a + b.
 *
 * This simple function is used for a smoke test.
 *
 * @param a {Number}
 * @param b {Number}
 * @return {Number}
 * */
__pulsar_utils__.add = function(a, b) {
    return a + b
};

/**
 * Press a key.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/KeyboardEvent/key)
 * */
__pulsar_utils__.press = function(selector, key) {
    let element = document.querySelector(selector)
    if (element != null) {
        element.dispatchEvent(new KeyboardEvent('keypress', {key: key}));
    }
};

/**
 * Return type information.
 *
 * @return {Object}
 * */
__pulsar_utils__.typeInfo = function() {
    return Object.keys(__pulsar_utils__).join(", ")
};

// --- Export API ---

// The Isolated World and the Page World share the same DOM (so you can manipulate the page, click buttons, etc.),
// However, the JavaScript global objects on both sides are isolated (each has its own window/ globalThis/ prototype chain),
// So when you execute window.__pulsar_utils__ = ...in the Isolated World, it is, by default, attached only to the window of the Isolated World,
// The page's own scripts (Page World) access the window of the Page World and cannot see the global variables of the Isolated World.
window.__pulsar_utils__ = __pulsar_utils__
window.__pulsar_CONFIGS = __pulsar_CONFIGS
window.__pulsar_NodeExt = __pulsar_NodeExt
window.__pulsar_TreeWalker = __pulsar_TreeWalker
window.__pulsar_NodeFeatureCalculator = __pulsar_NodeFeatureCalculator
