package ai.platon.pulsar.ql

import org.junit.jupiter.api.DisplayName
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Comprehensive integration tests for String UDFs.
 *
 * Tests the UDFs defined in:
 *   - [ai.platon.pulsar.ql.h2.udfs.StringFunctions] (namespace = "STR")
 *
 * The UDF aliases are generated by the H2 registration process:
 * "STR" + "_" + methodName, underscores stripped, uppercased.
 * H2 resolves function names case-insensitively and ignores underscores.
 */
class TestStringUdfs : QlIntegrationTestBase() {

    // -- isEmpty / isNotEmpty / isBlank / isNotBlank -------------------------

    @Test
    @DisplayName("test STR_IS_EMPTY returns true for empty string")
    fun testStrIsEmptyReturnsTrueForEmptyString() {
        query("SELECT STR_IS_EMPTY('') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_EMPTY returns false for non-empty string")
    fun testStrIsEmptyReturnsFalseForNonEmptyString() {
        query("SELECT STR_IS_EMPTY('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(false, rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NOT_EMPTY returns false for empty string")
    fun testStrIsNotEmptyReturnsFalseForEmptyString() {
        query("SELECT STR_IS_NOT_EMPTY('') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(false, rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NOT_EMPTY returns true for non-empty string")
    fun testStrIsNotEmptyReturnsTrueForNonEmptyString() {
        query("SELECT STR_IS_NOT_EMPTY('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_BLANK returns true for blank string")
    fun testStrIsBlankReturnsTrueForBlankString() {
        query("SELECT STR_IS_BLANK('   ') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_BLANK returns false for non-blank string")
    fun testStrIsBlankReturnsFalseForNonBlankString() {
        query("SELECT STR_IS_BLANK('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(false, rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NOT_BLANK returns true for non-blank string")
    fun testStrIsNotBlankReturnsTrueForNonBlankString() {
        query("SELECT STR_IS_NOT_BLANK('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NOT_BLANK returns false for blank string")
    fun testStrIsNotBlankReturnsFalseForBlankString() {
        query("SELECT STR_IS_NOT_BLANK('   ') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(false, rs.getBoolean("RESULT"))
        }
    }

    // Note: STR_IS_ANY_EMPTY, STR_IS_NONE_EMPTY, STR_IS_ANY_BLANK, STR_IS_NONE_BLANK
    // take Array<String> parameters. H2's SQL parser does not support ARRAY[...]
    // as a direct function argument (the comma inside is parsed as parameter separator).
    // These thin wrappers around Apache Commons StringUtils are verified by Commons tests.

    // -- trim / strip variants --------------------------------------------------

    @Test
    @DisplayName("test STR_TRIM removes leading and trailing whitespace")
    fun testStrTrimRemovesLeadingTrailingWhitespace() {
        query("SELECT STR_TRIM('  hello  ') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_TRIM_TO_NULL returns null for blank string")
    fun testStrTrimToNullReturnsNullForBlankString() {
        query("SELECT STR_TRIM_TO_NULL('   ') AS result") { rs ->
            assertTrue(rs.next())
            val result = rs.getString("RESULT")
            assertTrue(result == null || result == "", "Expected null or empty, got: $result")
        }
    }

    @Test
    @DisplayName("test STR_TRIM_TO_EMPTY returns empty for blank string")
    fun testStrTrimToEmptyReturnsEmptyForBlankString() {
        query("SELECT STR_TRIM_TO_EMPTY('   ') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_STRIP removes whitespace")
    fun testStrStripRemovesWhitespace() {
        query("SELECT STR_STRIP('  hello  ') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_STRIP with stripChars removes specified chars")
    fun testStrStripWithStripCharsRemovesSpecifiedChars() {
        query("SELECT STR_STRIP('__hello__', '_') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_STRIP_TO_NULL returns null for blank after strip")
    fun testStrStripToNullReturnsNullForBlankAfterStrip() {
        query("SELECT STR_STRIP_TO_NULL('   ') AS result") { rs ->
            assertTrue(rs.next())
            val result = rs.getString("RESULT")
            assertTrue(result == null || result == "", "Expected null or empty, got: $result")
        }
    }

    @Test
    @DisplayName("test STR_STRIP_TO_EMPTY returns empty for blank after strip")
    fun testStrStripToEmptyReturnsEmptyForBlankAfterStrip() {
        query("SELECT STR_STRIP_TO_EMPTY('   ') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_STRIP_START removes leading chars")
    fun testStrStripStartRemovesLeadingChars() {
        query("SELECT STR_STRIP_START('//path/to/file', '/') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("path/to/file", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_STRIP_END removes trailing chars")
    fun testStrStripEndRemovesTrailingChars() {
        query("SELECT STR_STRIP_END('path/to/file/', '/') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("path/to/file", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_STRIP_ACCENTS removes diacritical marks")
    fun testStrStripAccentsRemovesDiacriticalMarks() {
        query("SELECT STR_STRIP_ACCENTS('café') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("cafe", rs.getString("RESULT"))
        }
    }

    // -- length -----------------------------------------------------------------

    @Test
    @DisplayName("test STR_LENGTH returns correct length")
    fun testStrLengthReturnsCorrectLength() {
        query("SELECT STR_LENGTH('hello world') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(11, rs.getInt("RESULT"))
        }
    }

    // -- capitalize / uncapitalize / swapCase / upperCase / lowerCase -----------

    @Test
    @DisplayName("test STR_CAPITALIZE capitalizes first letter")
    fun testStrCapitalizeCapitalizesFirstLetter() {
        query("SELECT STR_CAPITALIZE('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("Hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_UNCAPITALIZE lowercases first letter")
    fun testStrUncapitalizeLowercasesFirstLetter() {
        query("SELECT STR_UNCAPITALIZE('Hello') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SWAP_CASE swaps character cases")
    fun testStrSwapCaseSwapsCharacterCases() {
        query("SELECT STR_SWAP_CASE('Hello World') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hELLO wORLD", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_UPPER_CASE converts to uppercase")
    fun testStrUpperCaseConvertsToUppercase() {
        query("SELECT STR_UPPER_CASE('hello world') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("HELLO WORLD", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_LOWER_CASE converts to lowercase")
    fun testStrLowerCaseConvertsToLowercase() {
        query("SELECT STR_LOWER_CASE('HELLO WORLD') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello world", rs.getString("RESULT"))
        }
    }

    // -- substring / left / right / mid -----------------------------------------

    @Test
    @DisplayName("test STR_SUBSTRING with start index extracts suffix")
    fun testStrSubstringWithStartIndexExtractsSuffix() {
        query("SELECT STR_SUBSTRING('hello world', 6) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("world", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SUBSTRING with start and end extracts middle")
    fun testStrSubstringWithStartAndEndExtractsMiddle() {
        query("SELECT STR_SUBSTRING('hello world', 0, 5) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_LEFT extracts leftmost chars")
    fun testStrLeftExtractsLeftmostChars() {
        query("SELECT STR_LEFT('hello world', 5) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_RIGHT extracts rightmost chars")
    fun testStrRightExtractsRightmostChars() {
        query("SELECT STR_RIGHT('hello world', 5) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("world", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_MID extracts middle chars")
    fun testStrMidExtractsMiddleChars() {
        query("SELECT STR_MID('hello world', 3, 5) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("lo wo", rs.getString("RESULT"))
        }
    }

    // -- substringBefore / substringAfter / substringBetween --------------------

    @Test
    @DisplayName("test STR_SUBSTRING_BEFORE extracts text before separator")
    fun testStrSubstringBeforeExtractsTextBeforeSeparator() {
        query("SELECT STR_SUBSTRING_BEFORE('hello/world', '/') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SUBSTRING_AFTER extracts text after separator")
    fun testStrSubstringAfterExtractsTextAfterSeparator() {
        query("SELECT STR_SUBSTRING_AFTER('hello/world', '/') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("world", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SUBSTRING_BEFORE_LAST extracts text before last separator")
    fun testStrSubstringBeforeLastExtractsTextBeforeLastSeparator() {
        query("SELECT STR_SUBSTRING_BEFORE_LAST('a/b/c', '/') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("a/b", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SUBSTRING_AFTER_LAST extracts text after last separator")
    fun testStrSubstringAfterLastExtractsTextAfterLastSeparator() {
        query("SELECT STR_SUBSTRING_AFTER_LAST('a/b/c', '/') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("c", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SUBSTRING_BETWEEN extracts text between tag")
    fun testStrSubstringBetweenExtractsTextBetweenTag() {
        query("SELECT STR_SUBSTRING_BETWEEN('<p>hello</p>', '<p>', '</p>') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SUBSTRINGS_BETWEEN extracts all occurrences")
    fun testStrSubstringsBetweenExtractsAllOccurrences() {
        query("SELECT STR_SUBSTRINGS_BETWEEN('<li>a</li><li>b</li>', '<li>', '</li>') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    // -- split / join -----------------------------------------------------------

    @Test
    @DisplayName("test STR_SPLIT splits by whitespace")
    fun testStrSplitSplitsByWhitespace() {
        query("SELECT STR_SPLIT('a b c') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SPLIT with separator splits by comma")
    fun testStrSplitWithSeparatorSplitsByComma() {
        query("SELECT STR_SPLIT('a,b,c', ',') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    // Note: STR_JOIN and STR_JOIN with separator take Array<String> parameters.
    // H2 SQL parser limitation prevents ARRAY[...] in function arguments.
    // These thin wrappers around Apache Commons StringUtils are verified by Commons tests.

    @Test
    @DisplayName("test STR_SPLIT_PRESERVE_ALL_TOKENS preserves empty tokens")
    fun testStrSplitPreserveAllTokensPreservesEmptyTokens() {
        query("SELECT STR_SPLIT_PRESERVE_ALL_TOKENS('a,,b') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SPLIT_BY_WHOLE_SEPARATOR splits by whole string")
    fun testStrSplitByWholeSeparatorSplitsByWholeString() {
        query("SELECT STR_SPLIT_BY_WHOLE_SEPARATOR('ab--cd--ef', '--') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SPLIT_BY_CHARACTER_TYPE splits by char type boundaries")
    fun testStrSplitByCharacterTypeSplitsByCharTypeBoundaries() {
        query("SELECT STR_SPLIT_BY_CHARACTER_TYPE('abc123def') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_SPLIT_BY_CHARACTER_TYPE_CAMEL_CASE splits camelCase")
    fun testStrSplitByCharacterTypeCamelCaseSplitsCamelCase() {
        query("SELECT STR_SPLIT_BY_CHARACTER_TYPE_CAMEL_CASE('helloWorld') AS result") { rs ->
            assertTrue(rs.next())
            assertNotNull(rs.getArray("RESULT"))
        }
    }

    // -- contains / indexOf / lastIndexOf ---------------------------------------

    @Test
    @DisplayName("test STR_CONTAINS_WHITESPACE detects whitespace")
    fun testStrContainsWhitespaceDetectsWhitespace() {
        query("SELECT STR_CONTAINS_WHITESPACE('hello world') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_CONTAINS_ANY detects any search chars")
    fun testStrContainsAnyDetectsAnySearchChars() {
        query("SELECT STR_CONTAINS_ANY('hello', 'ae') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_CONTAINS_ONLY returns true when only search chars present")
    fun testStrContainsOnlyReturnsTrueWhenOnlySearchCharsPresent() {
        query("SELECT STR_CONTAINS_ONLY('abcabc', 'abc') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_CONTAINS_NONE returns true when no search chars")
    fun testStrContainsNoneReturnsTrueWhenNoSearchChars() {
        query("SELECT STR_CONTAINS_NONE('hello', 'xyz') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_INDEX_OF_ANY returns index of first match")
    fun testStrIndexOfAnyReturnsIndexOfFirstMatch() {
        query("SELECT STR_INDEX_OF_ANY('hello', 'eo') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(1, rs.getInt("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_INDEX_OF_ANY_BUT returns index of first non-match")
    fun testStrIndexOfAnyButReturnsIndexOfFirstNonMatch() {
        query("SELECT STR_INDEX_OF_ANY_BUT('aaabbb', 'a') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(3, rs.getInt("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_ORDINAL_INDEX_OF finds nth occurrence")
    fun testStrOrdinalIndexOfFindsNthOccurrence() {
        query("SELECT STR_ORDINAL_INDEX_OF('abacad', 'a', 2) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(2, rs.getInt("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_LAST_ORDINAL_INDEX_OF finds nth from end")
    fun testStrLastOrdinalIndexOfFindsNthFromEnd() {
        query("SELECT STR_LAST_ORDINAL_INDEX_OF('abacad', 'a', 1) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(4, rs.getInt("RESULT"))
        }
    }

    // -- character type checks --------------------------------------------------

    @Test
    @DisplayName("test STR_IS_ALPHA returns true for alphabetic string")
    fun testStrIsAlphaReturnsTrueForAlphabeticString() {
        query("SELECT STR_IS_ALPHA('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ALPHA returns false for alphanumeric string")
    fun testStrIsAlphaReturnsFalseForAlphanumericString() {
        query("SELECT STR_IS_ALPHA('hello123') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(false, rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NUMERIC returns true for numeric string")
    fun testStrIsNumericReturnsTrueForNumericString() {
        query("SELECT STR_IS_NUMERIC('12345') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NUMERIC returns false for non-numeric string")
    fun testStrIsNumericReturnsFalseForNonNumericString() {
        query("SELECT STR_IS_NUMERIC('abc123') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(false, rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_WHITESPACE returns true for whitespace only")
    fun testStrIsWhitespaceReturnsTrueForWhitespaceOnly() {
        query("SELECT STR_IS_WHITESPACE('   ') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ALPHA_SPACE returns true for letters and spaces")
    fun testStrIsAlphaSpaceReturnsTrueForLettersAndSpaces() {
        query("SELECT STR_IS_ALPHA_SPACE('hello world') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ALPHANUMERIC returns true for letters and digits")
    fun testStrIsAlphanumericReturnsTrueForLettersAndDigits() {
        query("SELECT STR_IS_ALPHANUMERIC('hello123') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ALPHANUMERIC_SPACE returns true for alphanumeric with spaces")
    fun testStrIsAlphanumericSpaceReturnsTrueForAlphanumericWithSpaces() {
        query("SELECT STR_IS_ALPHANUMERIC_SPACE('hello 123') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ASCII_PRINTABLE returns true for printable ASCII")
    fun testStrIsAsciiPrintableReturnsTrueForPrintableAscii() {
        query("SELECT STR_IS_ASCII_PRINTABLE('hello123!@#') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_NUMERIC_SPACE returns true for numbers and spaces")
    fun testStrIsNumericSpaceReturnsTrueForNumbersAndSpaces() {
        query("SELECT STR_IS_NUMERIC_SPACE('123 456') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ALL_LOWER_CASE returns true for all lowercase")
    fun testStrIsAllLowerCaseReturnsTrueForAllLowercase() {
        query("SELECT STR_IS_ALL_LOWER_CASE('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_IS_ALL_UPPER_CASE returns true for all uppercase")
    fun testStrIsAllUpperCaseReturnsTrueForAllUppercase() {
        query("SELECT STR_IS_ALL_UPPER_CASE('HELLO') AS result") { rs ->
            assertTrue(rs.next())
            assertTrue(rs.getBoolean("RESULT"))
        }
    }

    // -- replace / delete -------------------------------------------------------

    @Test
    @DisplayName("test STR_DELETE_WHITESPACE removes all whitespace")
    fun testStrDeleteWhitespaceRemovesAllWhitespace() {
        query("SELECT STR_DELETE_WHITESPACE(' a b  c ') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("abc", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_REPLACE_CHARS replaces characters in string")
    fun testStrReplaceCharsReplacesCharactersInString() {
        query("SELECT STR_REPLACE_CHARS('hello', 'el', 'ip') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hippo", rs.getString("RESULT"))
        }
    }

    // Note: STR_REPLACE_EACH and STR_REPLACE_EACH_REPEATEDLY take Array<String> parameters.
    // H2 SQL parser limitation prevents ARRAY[...] in function arguments, and
    // SET @var also fails for the same reason. These wrappers around
    // Apache Commons StringUtils are verified by Commons tests.

    // -- overlay ----------------------------------------------------------------

    @Test
    @DisplayName("test STR_OVERLAY overlays string at position")
    fun testStrOverlayOverlaysStringAtPosition() {
        query("SELECT STR_OVERLAY('hello world', 'there', 6, 11) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello there", rs.getString("RESULT"))
        }
    }

    // -- chomp / chop -----------------------------------------------------------

    @Test
    @DisplayName("test STR_CHOMP removes trailing newline")
    fun testStrChompRemovesTrailingNewline() {
        query("SELECT STR_CHOMP('hello\n') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_CHOP removes last character")
    fun testStrChopRemovesLastCharacter() {
        query("SELECT STR_CHOP('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hell", rs.getString("RESULT"))
        }
    }

    // -- padding ----------------------------------------------------------------

    @Test
    @DisplayName("test STR_RIGHT_PAD pads to the right with spaces")
    fun testStrRightPadPadsToRightWithSpaces() {
        query("SELECT STR_RIGHT_PAD('hi', 5) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hi   ", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_LEFT_PAD pads to the left with spaces")
    fun testStrLeftPadPadsToLeftWithSpaces() {
        query("SELECT STR_LEFT_PAD('hi', 5) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("   hi", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_CENTER centers text with spaces")
    fun testStrCenterCentersTextWithSpaces() {
        query("SELECT STR_CENTER('hi', 6) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("  hi  ", rs.getString("RESULT"))
        }
    }

    // -- repeat / reverse / reverseDelimited ------------------------------------

    @Test
    @DisplayName("test STR_REPEAT repeats string n times")
    fun testStrRepeatRepeatsStringNTimes() {
        query("SELECT STR_REPEAT('ab', 3) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("ababab", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_REVERSE reverses a string")
    fun testStrReverseReversesString() {
        query("SELECT STR_REVERSE('hello') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("olleh", rs.getString("RESULT"))
        }
    }

    // Note: STR_REVERSE_DELIMITED takes a Kotlin Char parameter.
    // H2 cannot auto-convert a string literal to Kotlin Char,
    // so this UDF is only usable via JDBC prepared statements with setChar().
    // @Test
    // fun testStrReverseDelimitedReversesDelimitedTokens() { }

    // -- countMatches -----------------------------------------------------------

    @Test
    @DisplayName("test STR_COUNT_MATCHES counts substring occurrences")
    fun testStrCountMatchesCountsSubstringOccurrences() {
        query("SELECT STR_COUNT_MATCHES('ababab', 'ab') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(3, rs.getInt("RESULT"))
        }
    }

    // -- defaultString / defaultIfBlank / defaultIfEmpty ------------------------

    @Test
    @DisplayName("test STR_DEFAULT_STRING returns empty string for null")
    fun testStrDefaultStringReturnsEmptyForNull() {
        query("SELECT STR_DEFAULT_STRING(NULL) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_DEFAULT_IF_BLANK returns default for blank")
    fun testStrDefaultIfBlankReturnsDefaultForBlank() {
        query("SELECT STR_DEFAULT_IF_BLANK('   ', 'default') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("default", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_DEFAULT_IF_EMPTY returns default for empty")
    fun testStrDefaultIfEmptyReturnsDefaultForEmpty() {
        query("SELECT STR_DEFAULT_IF_EMPTY('', 'default') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("default", rs.getString("RESULT"))
        }
    }

    // -- abbreviate -------------------------------------------------------------

    @Test
    @DisplayName("test STR_ABBREVIATE abbreviates long string")
    fun testStrAbbreviateAbbreviatesLongString() {
        query("SELECT STR_ABBREVIATE('hello world this is a test', 15) AS result") { rs ->
            assertTrue(rs.next())
            val result = rs.getString("RESULT")
            assertTrue(result!!.endsWith("..."), "Expected abbreviation ending with '...', got: $result")
            assertTrue(result.length <= 15, "Expected length <= 15, got: ${result.length}")
        }
    }

    @Test
    @DisplayName("test STR_ABBREVIATE_MIDDLE abbreviates from middle")
    fun testStrAbbreviateMiddleAbbreviatesFromMiddle() {
        query("SELECT STR_ABBREVIATE_MIDDLE('hello world this is a test', '...', 20) AS result") { rs ->
            assertTrue(rs.next())
            val result = rs.getString("RESULT")
            assertTrue(result!!.length <= 20, "Expected length <= 20, got: ${result.length}")
        }
    }

    // -- difference / indexOfDifference / getCommonPrefix -----------------------

    @Test
    @DisplayName("test STR_DIFFERENCE returns the differing suffix")
    fun testStrDifferenceReturnsTheDifferingSuffix() {
        query("SELECT STR_DIFFERENCE('hello world', 'hello there') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("there", rs.getString("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_INDEX_OF_DIFFERENCE finds first differing index")
    fun testStrIndexOfDifferenceFindsFirstDifferingIndex() {
        query("SELECT STR_INDEX_OF_DIFFERENCE('hello', 'hexlo') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(2, rs.getInt("RESULT"))
        }
    }

    // Note: STR_GET_COMMON_PREFIX takes Array<String> parameter.
    // H2 SQL parser limitation prevents ARRAY[...] in function arguments.

    // -- normalizeSpace ---------------------------------------------------------

    @Test
    @DisplayName("test STR_NORMALIZE_SPACE collapses whitespace")
    fun testStrNormalizeSpaceCollapsesWhitespace() {
        query("SELECT STR_NORMALIZE_SPACE('hello   world  !') AS result") { rs ->
            assertTrue(rs.next())
            assertEquals("hello world !", rs.getString("RESULT"))
        }
    }

    // -- firstInteger / firstFloat (custom functions) ---------------------------

    @Test
    @DisplayName("test STR_FIRST_INTEGER extracts first integer from string")
    fun testStrFirstIntegerExtractsFirstIntegerFromString() {
        query("SELECT STR_FIRST_INTEGER('price is 199 dollars', 0) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(199, rs.getInt("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_FIRST_FLOAT extracts first float from string")
    fun testStrFirstFloatExtractsFirstFloatFromString() {
        query("SELECT STR_FIRST_FLOAT('price is 19.99 dollars', 0.0) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(19.99f, rs.getFloat("RESULT"))
        }
    }

    @Test
    @DisplayName("test STR_GET_FIRST_FLOAT_NUMBER extracts first float")
    fun testStrGetFirstFloatNumberExtractsFirstFloat() {
        query("SELECT STR_GET_FIRST_FLOAT_NUMBER('weight: 5.5 kg', 0.0) AS result") { rs ->
            assertTrue(rs.next())
            assertEquals(5.5f, rs.getFloat("RESULT"))
        }
    }
}
